## Apendix {-}

Create `by_quarter` data

```{r}
by_quarter %>% write_csv("exercises/surveys-by-quarter.csv")
```


Create weather data for lesson

```{r create-portal-weather-subset, eval=FALSE}
set.seed(1792)
# Species data
weather <- read_csv("https://raw.githubusercontent.com/weecology/PortalData/master/Weather/Portal_weather.csv",
                    col_types = cols(RH = col_double(),
                                     battv = col_double(),
                                     PTemp_C = col_double(),
                                     BP_mmHg_Avg = col_double(),
                                     SlrkW = col_double(),
                                     SlrMJ_Tot = col_double(),
                                     ETos =col_double(),
                                     Rso = col_double(),
                                     WS_ms_Avg = col_double(),
                                     WindDir  = col_double(),
                                     WS_ms_S_WVT= col_double(),
                                     WindDir_D1_WVT = col_double(),
                                     WindDir_SD1_WVT = col_double(),
                                     HI_C_Avg = col_double(),     
                                     SunHrs_Tot = col_double(),
                                     PotSlrW_Avg = col_double(), 
                                     WC_C_Avg = col_double()
                                     )) %>% 
        mutate(date = make_date(day = day, month = month, year = year), 
               plot = sample(1:24,252047,replace=T))

weather %>% select(date,plot,airtemp,precipitation) %>%
        group_by(plot,date) %>% 
        summarise(avg_temp = median(airtemp, na.rm = T), 
                  avg_rain = mean(precipitation, na.rm = T)) %>% 
write_csv("exercises/portal-weather-subset.csv")
```

Create rodent data for lesson

```{r rodent-data eval=FALSE}
# Rodent survey data
rodent_data <-  read_csv("https://raw.githubusercontent.com/weecology/PortalData/master/Rodents/Portal_rodent.csv",
                         col_types = cols(tag = col_character(),
                                         prevrt = col_character(),
                                         ltag = col_character(),
                                         note2 = col_character(),
                                         note3 = col_character(), 
                                         note4 = col_character(), 
                                         note5 = col_character())) %>% 
        mutate(date = make_date(day = day, month = month, year = year))

rodent_data %>% select(date,plot,species,sex,hfl,wgt) %>%
        filter(date >= '1989-06-04')%>% 
        write_csv("exercises/portal_rodent.csv")
```

```{r read-rodent, cache=TRUE,eval=FALSE}
# Rodent survey data
rodent_data <-  read_csv("https://raw.githubusercontent.com/ab604/coding-together/master/exercises/portal_rodent.csv")
```

Take a look:

```{r glimpse-rd}
rodent_data
```


```{r read-weather, eval=FALSE}
weather <- read_csv("https://raw.githubusercontent.com/ab604/coding-together/master/exercises/portal-weather-subset.csv")
```

Take a look:

```{r glimpse-weather}
weather
```

Stocks date for missing value

```{r}
stocks <- tibble(
  year   = c(2015, 2015, 2015, 2015, 2016, 2016, 2016),
  qtr    = c(   1,    2,    3,    4,    2,    3,    4),
  return = c(1.88, 0.59, 0.35,   NA, 0.92, 0.17, 2.66)
)

stocks %>% write_csv("exercises/stocks.csv")
```

Surveys with missing values

```{r}
# Create a table with missing values
surveys_ms <- tibble(year = c(1991,1991,1991,1991,1992,1992,1992),
                     qtr = c(1,2,3,4,1,2,4),
                     mean_weight = c(3.75,2.50,NA,8.50,7.50,2.25,2.50))

surveys_ms %>% write_csv("exercises/surveys_ms.csv")
```

