<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Coding togetheR</title>
  <meta name="description" content="Materials for the Coding TogetheR workshops" />
  <meta name="generator" content="bookdown #bookdown:version# and GitBook 2.6.7" />

  <meta property="og:title" content="Coding togetheR" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="<a href="https://ab604.github.io/docs/coding-together-2019/" class="uri">https://ab604.github.io/docs/coding-together-2019/</a>" />
  <meta property="og:image" content="<a href="https://ab604.github.io/docs/coding-together-2019/" class="uri">https://ab604.github.io/docs/coding-together-2019/</a>img/Carrick-bend-Guten-Verrill-modified.png" />
  <meta property="og:description" content="Materials for the Coding TogetheR workshops" />
  <meta name="github-repo" content="ab604/coding-together" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Coding togetheR" />
  <meta name="twitter:site" content="@alistair604" />
  <meta name="twitter:description" content="Materials for the Coding TogetheR workshops" />
  <meta name="twitter:image" content="<a href="https://ab604.github.io/docs/coding-together-2019/" class="uri">https://ab604.github.io/docs/coding-together-2019/</a>img/Carrick-bend-Guten-Verrill-modified.png" />

<meta name="author" content="Alistair Bailey" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<!--bookdown:link_prev-->
<!--bookdown:link_next-->
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



<!--bookdown:title:start-->
<div id="header">
<h1 class="title">Coding togetheR</h1>
<p class="author"><em>Alistair Bailey</em></p>
<p class="date"><em>October 24 2019</em></p>
</div>
<!--bookdown:title:end-->

<!--bookdown:toc:start-->
  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">
<!--bookdown:toc2:start-->
<ul>
<li><a href="#welcome">Welcome</a><ul>
<li><a href="#r-and-rstudio">R and RStudio</a></li>
<li><a href="#who-is-coding-together-for">Who is coding togetheR for?</a></li>
<li><a href="#code-of-conduct">Code of conduct</a></li>
</ul></li>
<li><a href="#getting-started"><span class="toc-section-number">1</span> Getting started</a><ul>
<li><a href="#coding-is-for-everyone"><span class="toc-section-number">1.1</span> Coding is for everyone</a></li>
<li><a href="#a-little-background-and-philosophy"><span class="toc-section-number">1.2</span> A little background and philosophy</a><ul>
<li><a href="#what-is-r"><span class="toc-section-number">1.2.1</span> What is R?</a></li>
<li><a href="#why-learn-to-code-at-all"><span class="toc-section-number">1.2.2</span> Why learn to code at all?</a></li>
<li><a href="#a-little-goes-a-long-way"><span class="toc-section-number">1.2.3</span> A little goes a long way</a></li>
</ul></li>
<li><a href="#rstudio"><span class="toc-section-number">1.3</span> RStudio</a><ul>
<li><a href="#what-is-real"><span class="toc-section-number">1.3.1</span> What is real?</a></li>
<li><a href="#file-structure"><span class="toc-section-number">1.3.2</span> Where am I?</a></li>
</ul></li>
<li><a href="#install-packages"><span class="toc-section-number">1.4</span> Installing and loading packages</a></li>
<li><a href="#functions-1"><span class="toc-section-number">1.5</span> Using functions</a></li>
<li><a href="#getting-help"><span class="toc-section-number">1.6</span> Getting help</a><ul>
<li><a href="#using-to-access-r-function-help-pages"><span class="toc-section-number">1.6.1</span> Using <code>?</code> to access R function help pages</a></li>
<li><a href="#using-google-to-find-r-answers"><span class="toc-section-number">1.6.2</span> Using Google to find R answers</a></li>
<li><a href="#asking-questions"><span class="toc-section-number">1.6.3</span> Asking questions</a></li>
</ul></li>
<li><a href="#workflow"><span class="toc-section-number">1.7</span> A project orientated workflow</a><ul>
<li><a href="#rstudio-projects"><span class="toc-section-number">1.7.1</span> RStudio Projects</a></li>
<li><a href="#r-notebooks-and-r-scripts"><span class="toc-section-number">1.7.2</span> R notebooks and R scripts</a></li>
<li><a href="#here"><span class="toc-section-number">1.7.3</span> Level up with the <code>here</code> package</a></li>
<li><a href="#names"><span class="toc-section-number">1.7.4</span> Naming things</a></li>
</ul></li>
<li><a href="#tidy-data"><span class="toc-section-number">1.8</span> The tidyverse and tidy data</a></li>
<li><a href="#r-atoms"><span class="toc-section-number">1.9</span> Atoms of R</a></li>
<li><a href="#assignment"><span class="toc-section-number">1.10</span> Assigning objects</a><ul>
<li><a href="#indexing-and-subsetting"><span class="toc-section-number">1.10.1</span> Indexing and subsetting</a></li>
</ul></li>
<li><a href="#lists-matrices-and-arrays"><span class="toc-section-number">1.11</span> Lists, matrices and arrays</a><ul>
<li><a href="#matrices-and-arrays"><span class="toc-section-number">1.11.1</span> Matrices and arrays</a></li>
</ul></li>
<li><a href="#factors"><span class="toc-section-number">1.12</span> Factors</a></li>
<li><a href="#data-frames"><span class="toc-section-number">1.13</span> Data frames</a><ul>
<li><a href="#attributes"><span class="toc-section-number">1.13.1</span> Attributes</a></li>
</ul></li>
<li><a href="#plotting-data"><span class="toc-section-number">1.14</span> Plotting data</a></li>
<li><a href="#exporting-data"><span class="toc-section-number">1.15</span> Exporting data</a><ul>
<li><a href="#readr"><span class="toc-section-number">1.15.1</span> readr</a></li>
<li><a href="#ggsave"><span class="toc-section-number">1.15.2</span> ggsave</a></li>
<li><a href="#exercise"><span class="toc-section-number">1.15.3</span> Exercise</a></li>
</ul></li>
</ul></li>
<li><a href="#data-wrangle-1"><span class="toc-section-number">2</span> Data wrangling I</a><ul>
<li><a href="#data-organisation-in-spreadsheets"><span class="toc-section-number">2.1</span> Data organisation in spreadsheets</a><ul>
<li><a href="#flat-formats-and-excel-files"><span class="toc-section-number">2.1.1</span> Flat formats and Excel files</a></li>
</ul></li>
<li><a href="#portal-project"><span class="toc-section-number">2.2</span> The Portal Project data</a><ul>
<li><a href="#downloading-and-importing-the-data"><span class="toc-section-number">2.2.1</span> Downloading and importing the data</a></li>
</ul></li>
<li><a href="#dplyr"><span class="toc-section-number">2.3</span> <code>dplyr</code></a><ul>
<li><a href="#filter-rows-with-filter"><span class="toc-section-number">2.3.1</span> Filter rows with <code>filter()</code></a></li>
<li><a href="#arrange-rows-with-arrange"><span class="toc-section-number">2.3.2</span> Arrange rows with <code>arrange()</code></a></li>
<li><a href="#select-columns-with-select"><span class="toc-section-number">2.3.3</span> Select columns with <code>select()</code></a></li>
<li><a href="#create-new-variables-with-mutate"><span class="toc-section-number">2.3.4</span> Create new variables with <code>mutate()</code></a></li>
<li><a href="#grouped-summaries-with-group_by-and-summarise"><span class="toc-section-number">2.3.5</span> Grouped summaries with <code>group_by()</code> and <code>summarise()</code></a></li>
</ul></li>
<li><a href="#using-dpylr-to-explore-the-effect-of-kangaroo-rat-exclusion-on-granivore-populations"><span class="toc-section-number">2.4</span> Using <code>dpylr</code> to explore the effect of Kangaroo Rat exclusion on Granivore populations</a><ul>
<li><a href="#re-cap-of-filter-and-mutate"><span class="toc-section-number">2.4.1</span> Re-cap of <code>filter()</code> and <code>mutate()</code></a></li>
<li><a href="#use-lubridate-to-create-new-time-variables"><span class="toc-section-number">2.4.2</span> Use <code>lubridate</code> to create new time variables</a></li>
<li><a href="#group-and-summarise-the-data-into-quarterly-observations"><span class="toc-section-number">2.4.3</span> Group and summarise the data into quarterly observations</a></li>
<li><a href="#create-a-plot-with-ggplot"><span class="toc-section-number">2.4.4</span> Create a plot with <code>ggplot</code></a></li>
</ul></li>
</ul></li>
<li><a href="#data-wrangle-2"><span class="toc-section-number">3</span> Data wrangling II</a><ul>
<li><a href="#reshaping-data-with-pivots"><span class="toc-section-number">3.1</span> Reshaping data with pivots</a><ul>
<li><a href="#tidyrpivot_longer"><span class="toc-section-number">3.1.1</span> <code>tidyr::pivot_longer</code></a></li>
<li><a href="#tidyrpivot_wider"><span class="toc-section-number">3.1.2</span> <code>tidyr::pivot_wider</code></a></li>
</ul></li>
</ul></li>
</ul>
<!--bookdown:toc2:end-->
      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Coding togetheR</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!--bookdown:toc:end-->
<!--bookdown:body:start-->
<div id="welcome" class="section level1 unnumbered">
<h1>Welcome</h1>
<p><img src="img/carrick-bend.png" width="60%" style="display: block; margin: auto;" /></p>
<blockquote>
<p><a href="https://en.wikipedia.org/wiki/File:Carrick-bend-Guten-Verrill-modified.png">A Carrick bend:</a> The Carrick bend is a type of sailor’s knot used for joining two lines.</p>
</blockquote>
<p>Coding togetheR is a series of collaborative workshops to teach
foundational R coding and data science skills at the University of Southampton
in 2019. This book contains the materials covered over eight, two hour sessions.</p>
<p>The workshops are for anyone at the University of Southampton with data to analyse and who is struggling with their current tools. This series of eight weekly two hour workshops provides an introduction to working with data using R in a supported environment. Unlike traditional lessons, we all code together with the emphasis on participants learning by doing and by helping each other.</p>
<p>These materials are a mash-up of my own and many others. I’ve endeavoured to
credit everyone appropriately, but please message <a href="https://ab604.uk/">me</a> if I’ve messed up and I’ll correct it.
The main sources used here are: <a href="https://r4ds.had.co.nz/">R for data science (R4DS)</a>,
<a href="https://www.rfordatasci.com/">the R4DS community</a>, <a href="https://carpentries.org/">the Carpentries</a>,
<a href="https://rstudio-education.github.io/hopr/">Hands on Programming in R</a>,
<a href="https://swirlstats.com/">swiRlstats</a> and
<a href="http://teachtogether.tech/en/">Teaching Tech togetheR</a>.</p>
<p>It was written using R <span class="citation">(R Core Team <a href="#ref-R-base" role="doc-biblioref">2019</a>)</span> in RStudio
<span class="citation">(RStudio Team <a href="#ref-rstudioteam2018" role="doc-biblioref">2018</a>)</span> using the bookdown package <span class="citation">(Xie <a href="#ref-R-bookdown" role="doc-biblioref">2019</a>)</span>.</p>
<p>To follow these materials you will need an up to date version of R <span class="citation">(R Core Team <a href="#ref-R-base" role="doc-biblioref">2019</a>)</span> and RStudio
<span class="citation">(RStudio Team <a href="#ref-rstudioteam2018" role="doc-biblioref">2018</a>)</span>. This may require requesting permission to install software
from Isolutions if you have a University laptop.</p>
<div id="r-and-rstudio" class="section level2 unnumbered">
<h2>R and RStudio</h2>
<p>If you are new to R, then the first thing
to know is that R is a programming language and RStudio is a
program for working with R called an integrated development
environment (IDE). You can use R without RStudio, but not the other way around.
Further details in Chapter @ref(getting-started).</p>
<p><a href="https://cran.r-project.org/">Download R here</a> and
<a href="https://www.rstudio.com/products/rstudio/download/">Download RStudio Desktop here</a>.</p>
<p>These materials were generated using R version 3.6.</p>
<p>Once you’ve installed R and RStudio, you’ll also need
a few R packages. Packages are collections of <a href="#function-anatomy">functions</a>.</p>
<p>Open RStudio and put the code below into the <code>Console</code>
window and press <code>Enter</code> to install the <code>tidyverse</code>,<code>dslabs</code>,<code>janitor</code> and <code>here</code> packages.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">install.packages</span>(<span class="kw">c</span>(<span class="st">&quot;tidyverse&quot;</span>,<span class="st">&quot;dslabs&quot;</span>,<span class="st">&quot;janitor&quot;</span>,<span class="st">&quot;here&quot;</span>))</a></code></pre></div>
</div>
<div id="who-is-coding-together-for" class="section level2 unnumbered">
<h2>Who is coding togetheR for?</h2>
<p>Following the lesson design process of <span class="citation">(Wilson <a href="#ref-Wilson2018" role="doc-biblioref">2018</a>)</span>:</p>
<p><strong>Arshad</strong></p>
<blockquote>
<p>As a PhD student in ecology Arshad doesn’t have any formal coding training,
but is gathering field data about bird populations. He is daunted by
the prospect of learning to code. These lessons will introduce Arshad to coding
by showing him how to organise and automate analysis of his data.</p>
</blockquote>
<p><strong>Jenny</strong></p>
<blockquote>
<p>As a post doctoral researcher in gerontology Jenny has experience of research, but
is unsatisfied with her current spreadsheet tools for analysing data. These
lessons will show her how to write code to analyse spreadsheets.</p>
</blockquote>
<p><strong>Lin</strong></p>
<blockquote>
<p>As a principal investigator Lin has experience using MATLAB, but has
not used R and would like to know more about it. These lessons will introduce
Lin to R syntax and RStudio workflows.</p>
</blockquote>
</div>
<div id="code-of-conduct" class="section level2 unnumbered">
<h2>Code of conduct</h2>
<p>Coding togetheR is for everyone, and in order to make it a supportive and
inclusive environment we subscribe to the <a href="https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html">Carpentries Code of Conduct</a>.
Please follow the link for details.</p>
<p>In a nutshell, expected behaviour is as follows:</p>
<ul>
<li>Use welcoming and inclusive language</li>
<li>Be respectful of different viewpoints and experiences</li>
<li>Gracefully accept constructive criticism</li>
<li>Focus on what is best for the community</li>
<li>Show courtesy and respect towards other community members</li>
</ul>
<p>Participants who violate the code of conduct, will be asked to stop immediately and if
necessary asked to leave the workshop and incidents reported as per <a href="https://www.southampton.ac.uk/studentservices/need-help/student-discipline/staff-information.page">University guidance
on inappropriate behaviour</a>.</p>
<!--chapter:end:index.Rmd-->
</div>
</div>
<div id="getting-started" class="section level1">
<h1><span class="header-section-number">1</span> Getting started</h1>
<p>By the end of this chapter are you will:</p>
<ul>
<li>understand how to install packages in RStudio.</li>
<li>know how to get help when you are stuck.</li>
<li>have set-up your first R project.</li>
<li>understand the atoms of R and how to use them to build data frames.</li>
<li>understand how to assign objects in R.</li>
<li>have created a plot using the <code>ggplot2</code> package.</li>
<li>have written outputs from R to files.</li>
</ul>
<div id="coding-is-for-everyone" class="section level2">
<h2><span class="header-section-number">1.1</span> Coding is for everyone</h2>
<p>If, when faced with the thought of starting to learning to code you feel like the cat in Figure @ref(fig:imposter).</p>
<p>(ref:imposter) <a href="https://bloggerbyresearch.files.wordpress.com/2015/04/a-baa-fail-cat-among-penguins.jpg">Imposter syndrome</a>.</p>
<div class="figure" style="text-align: center">
<img src="img/a-baa-fail-cat-among-penguins.jpg" alt="(ref:imposter)" width="80%" />
<p class="caption">
(#fig:imposter)(ref:imposter)
</p>
</div>
<p>Then hopefully by the end of these materials, you’ll feel a bit more like the cat in Figure @ref(fig:rcat).</p>
<p>(ref:r-cat) <a href="https://stephensontam.files.wordpress.com/2017/06/lolcat-programmer.jpg">R cat</a></p>
<div class="figure" style="text-align: center">
<img src="img/lolcat-programmer.jpg" alt="(ref:r-cat)" width="80%" />
<p class="caption">
(#fig:rcat)(ref:r-cat)
</p>
</div>
<p>And if you like that, there is more at <a href="https://www.rforcats.net/">R for cats</a>.</p>
</div>
<div id="a-little-background-and-philosophy" class="section level2">
<h2><span class="header-section-number">1.2</span> A little background and philosophy</h2>
<p><strong><em>“There are only two kinds of languages: the ones people complain about and the ones nobody uses”</em></strong></p>
<p><em>Bjarne Stroustrup, the inventor C++</em></p>
<div id="what-is-r" class="section level3">
<h3><span class="header-section-number">1.2.1</span> What is R?</h3>
<p><strong>R</strong> is a programming language that follows the philosophy laid down by it’s
predecessor S. The philosophy being that users begin in an interactive
environment where they don’t consciously think of themselves as programming.
It was created in 1993, and documented in <span class="citation">(Ihaka and Gentleman <a href="#ref-ihaka1996" role="doc-biblioref">1996</a>)</span>.</p>
<p>Reasons R has become popular include that it is both open source and cross platform,
and that it has broad functionality, from the analysis of data and creating
powerful graphical visualisations and web apps.</p>
<p>Like all languages though it has limitations, for example the syntax is initially
confusing.</p>
<p>Users and developers of R have in recent years sought to develop an inclusive
and welcoming community which can found on twitter <code>#rstats</code> or
through <a href="https://community.rstudio.com/">RStudio Community</a>.
There are many useR groups, including groups seeking to promote diversity such
as <a href="https://rladies.org/about-us/">R-Ladies</a>: <a href="https://jumpingrivers.github.io/meetingsR/">Jumping Rivers maintains a list</a>.</p>
</div>
<div id="why-learn-to-code-at-all" class="section level3">
<h3><span class="header-section-number">1.2.2</span> Why learn to code at all?</h3>
<p>In terms of the philosophy of learning to code:</p>
<ol style="list-style-type: decimal">
<li><p>The primary motivation for using tools such as R is to get more done, in
less time and with less pain.</p></li>
<li><p>And the overall aim is to <em>understand and communicate</em> findings from our
data.</p></li>
<li><p>Additionally, as per <a href="http://third-bit.com/2019/01/30/why-i-teach.html">Greg Wilson’s description of his motivation for teaching</a>, if we’re going
to help make the world a better place, a bit of coding is likely to be
key tool in your kit.</p></li>
</ol>
<p>(ref:pipeline) Data project workflow.</p>
<div class="figure" style="text-align: center">
<img src="img/data_project_pipeline.png" alt="(ref:pipeline)" width="80%" />
<p class="caption">
(#fig:pipeline)(ref:pipeline)
</p>
</div>
<p>As shown in Figure @ref(fig:pipeline) of typical data analysis workflow,
to achieve this aim we need to learn tools that enable us to perform the
fundamental tasks of tasks of importing, tidying and
often transforming the data. Transformation means for example, selecting a
subset of the data to work with, or calculating the mean of a set of observations.</p>
</div>
<div id="a-little-goes-a-long-way" class="section level3">
<h3><span class="header-section-number">1.2.3</span> A little goes a long way</h3>
<p>Returning to our cat friend in Figure @ref(fig:rcat), one doesn’t need to be an expert programmer to find coding useful. As illustrated in Figure @ref(fig:prac-prog)
there is a whole spectrum of code users from
practitioners who are focused on applying some R to their specific problems, to those
programmers who develop the R language itself. In reality one may move
around on that spectrum as ones interests change over time.</p>
<p>(ref:pp) The Practitioner-Programmer spectrum</p>
<div class="figure" style="text-align: center">
<img src="img/practioner-programmer.png" alt="(ref:pp)" width="80%" />
<p class="caption">
(#fig:prac-prog)(ref:pp)
</p>
</div>
</div>
</div>
<div id="rstudio" class="section level2">
<h2><span class="header-section-number">1.3</span> RStudio</h2>
<p>Let’s begin by learning about <a href="https://www.rstudio.com/">RStudio</a>, the
Integrated Development Environment (IDE).</p>
<p><strong>R is the language and RStudio is software created to facilitate our use of R.</strong>
They are installed separately. You don’t need RStudio to use R, but you do need
R to used RStudio.</p>
<p>We will use R Studio IDE to write code, navigate the files found on our computer,
inspect the variables we are going to create, and visualize the plots we will
generate. R Studio can also be used for other things (e.g., version control,
developing packages, writing Shiny apps) that we don’t have time to cover during
this workshop.</p>
<p>R Studio is divided into “Panes”, see Figure @ref(fig:rstudio).</p>
<p>When you first open it, there are three panes,the console where you type
commands, your environment/history (top-right), and your
files/plots/packages/help/viewer (bottom-right).</p>
<p>The environment shows all the R objects you have created or are using, such
as data you have imported.</p>
<p>The output pane can be used to view any plots you have created.</p>
<p>Not opened at first start up is the fourth default pane: the script editor pane,
but this will open as soon as we create/edit a R script (or many other document types).
<em>The script editor is where will be typing much of the time.</em></p>
<p>(ref:rstudio) The RStudio Integrated Development Environment (IDE).</p>
<div class="figure" style="text-align: center">
<img src="img/rstudio_ide_image.png" alt="(ref:rstudio)" width="80%" />
<p class="caption">
(#fig:rstudio)(ref:rstudio)
</p>
</div>
<p>The placement of these panes and their content can be customized (see menu,
R Studio -&gt; Tools -&gt; Global Options -&gt; Pane Layout). One of the advantages of
using R Studio is that all the information you need to write code is available
in a single window. Additionally, with many short-cuts, auto-completion, and
highlighting for the major file types you use while developing in R, R Studio
will make typing easier and less error-prone.</p>
<blockquote>
<p>RStudio has lots of keyboard short-cuts to make coding quicker and easier.
Try to find the menu listing all the keyboard short-cuts, including the short-cut
to find the menu!</p>
</blockquote>
<p>Time for another philosophical diversion…</p>
<div id="what-is-real" class="section level3">
<h3><span class="header-section-number">1.3.1</span> What is real?</h3>
<p>At the start, we might consider our environment “real” - that is to say the objects
we’ve created/loaded and are using are “real”. But it’s much better in the long run
to consider our scripts as “real” - our scripts are where we write down the code
that creates our objects that we’ll be using in our environment.</p>
<p><strong>As a script is a document, it is reproducible</strong></p>
<p>Or to put it another way: we can easily recreate an environment from our scripts,
but not so easily create a script from an environment.</p>
<p>To support this notion of thinking in terms of our scripts as real, we recommend
turning off the preservation of workspaces between sessions by setting the
Tools &gt; Global Options menu in R studio as shown in Figure @ref(fig:workspace).</p>
<p>(ref:turn-off) Don’t save your workspace, save your script instead.</p>
<div class="figure" style="text-align: center">
<img src="img/rdata_turn_off.png" alt="(ref:turn-off)" width="80%" />
<p class="caption">
(#fig:workspace)(ref:turn-off)
</p>
</div>
</div>
<div id="file-structure" class="section level3">
<h3><span class="header-section-number">1.3.2</span> Where am I?</h3>
<p>The part of your computer operating system that manages files and directories (aka folders)
is called the file system. This dates back to 1969 and the <a href="https://en.wikipedia.org/wiki/Unix_filesystem">Unix filesystem</a>.</p>
<p>The idea is that we have a rooted tree, as with <a href="https://en.wikipedia.org/wiki/Phylogenetic_tree#Rooted_tree">phylogenetic rooted trees</a> in biology.
From the root all other directories and files exist along paths going back to
the root as shown in Figure @ref(fig:abs-path).</p>
<p>On Unix based systems such as Apple or Android, the root is denoted with <code>/</code>. On
Windows the root is a back slash <code>\</code>. The <code>/</code> or <code>\</code> is used to
to separate directories along the path, denoting a change in the level of the tree</p>
<p><strong>Note: in RStudio the path separator and root is always <code>/</code> regardless of the operating system.</strong></p>
<div id="absolute-path-from-the-root" class="section level4">
<h4><span class="header-section-number">1.3.2.1</span> Absolute path from the root <code>/</code></h4>
<p>In Figure @ref(fig:abs-path) the absolute path from the root of <code>surveys.csv</code> is shown. In
text this would be <code>/users/alistair/Documents/coding-together-week-02/data/surveys.csv</code>.</p>
<p>This is just a made-up example and the path on your machine will be different.</p>
<p>(ref:abs-path) The red line shows the absolute path from the root <code>/</code> to <code>surveys.csv</code>.</p>
<div class="figure" style="text-align: center">
<img src="img/abs-filepath-23-10-2019.png" alt="(ref:abs-path)" width="100%" />
<p class="caption">
(#fig:abs-path)(ref:abs-path)
</p>
</div>
</div>
<div id="relative-path-from-where-you-are-.." class="section level4">
<h4><span class="header-section-number">1.3.2.2</span> Relative path from where you are <code>../</code></h4>
<p>However, we can also consider relative paths, that is relative to where we are
working at present.</p>
<p>In Figure @ref(fig:rel-path) I imagine that I am working in the <code>R</code> directory
in <code>coding-together-week-01</code> folder. To access the <code>surveys.csv</code> file I have to go up
two levels to <code>Documents</code> and then back down three levels. I could use the
absolute path, but <em>if</em> I know where <code>surveys.csv</code> is then I can use the short-hand of <code>../</code>
to go up one level, and then again to go up another, and then back down.</p>
<p>In text from the <code>R</code> directory this is: <code>../../coding-together-week-02/data/surveys.csv</code></p>
<p>I don’t reccomend this, it was just to illustrate what a relative path looks like.</p>
<p>(ref:rel-path) The red line represents the relative path from <code>R</code> to <code>surveys.csv</code></p>
<div class="figure" style="text-align: center">
<img src="img/rel-filepath-23-10-2019.png" alt="(ref:rel-path)" width="100%" />
<p class="caption">
(#fig:rel-path)(ref:rel-path)
</p>
</div>
</div>
<div id="home-directory-path" class="section level4">
<h4><span class="header-section-number">1.3.2.3</span> Home directory path <code>~</code></h4>
<p>The home directory is the part of the file system dedicated to the user - that’s us! -
and our data. Usually when we get a new computer we’ll have a home directory with
our user name. On Windows machines this will contain <code>My Documents</code> etc. and on
an Apple machine it will be <code>Documents</code> etc. On a shared machine each user will
get a home directory associated with their user name.</p>
<p>Because we are usually working in our home directory and it’s tiresome to keep
typing out paths from the root and it takes up room on the screen, the tilde <code>~</code> denotes the
path from the root to our home directory.</p>
<p>We can use the <code>~</code> to precede the rest of the path to shortcut an absolute path to the root.</p>
<p>Figure @ref(fig:home-path) indicates a home directory path to the
<code>surveys.csv</code> with the <code>~</code> part in blue and the remaining path in red.</p>
<p>In text this would be: <code>~/Documents/coding-together-week-02/data/surveys.csv</code></p>
<p>(ref:home-path) The home directory path to the
<code>surveys.csv</code> with the <code>~</code> part in blue and the remaining path in red.</p>
<div class="figure" style="text-align: center">
<img src="img/home-filepath-23-10-2019.png" alt="(ref:home-path)" width="100%" />
<p class="caption">
(#fig:home-path)(ref:home-path)
</p>
</div>
</div>
<div id="working-directory" class="section level4">
<h4><span class="header-section-number">1.3.2.4</span> Working directory</h4>
<p>R studio tells you where you are in terms of directory address as shown in
Figure @ref(fig:working-directory). Here this is a home directory path.</p>
<p>(ref:working-dir) Your working directory</p>
<div class="figure" style="text-align: center">
<img src="img/rstudio_working_directory.png" alt="(ref:working-dir)" width="80%" />
<p class="caption">
(#fig:working-directory)(ref:working-dir)
</p>
</div>
<p>It is good practice to keep a set of related data, analyses, and text
self-contained in a single folder, called <strong>your working directory</strong>. All of the
scripts within this folder can then use <em>relative paths</em> to files that indicate
where inside the project a file is located (as opposed to absolute paths, which
point to where a file is on a specific computer). An example
directory structure is illustrated in Figure @ref(fig:dir-structure).
Working this way makes it a lot easier to move your project around on your computer.
Section @ref(workflow) builds upon this to create a robust workflow for data analysis.</p>
<p>(ref:dir-structure) A typical directory structure</p>
<div class="figure" style="text-align: center">
<img src="img/R-ecology-work_dir_structure.png" alt="(ref:dir-structure)" width="80%" />
<p class="caption">
(#fig:dir-structure)(ref:dir-structure)
</p>
</div>
</div>
</div>
</div>
<div id="install-packages" class="section level2">
<h2><span class="header-section-number">1.4</span> Installing and loading packages</h2>
<p>Packages are collections of functions, and a function is a piece of code written
to perform a specific task, such as installing a package.</p>
<p>Therefore, the function <code>install.packages()</code> is a piece of code written to
perform the task of installing packages. We use it by typing <code>install.packages("tidyverse")</code>
with the name of the package in quotes inside the round brackets. Here
the package is <code>tidyverse</code>. Using the console
panel to type this and pressing <code>Enter</code> will run the function.</p>
<p>We of course need to know the name of the packages we are interested in.</p>
<p>Once a package is installed we need to load it into our environment to use it.
Loading packages is performed using the <code>library()</code> function. As with
installation, we put the name of the package we want to load in between
the round brackets like so <code>library(tidyverse)</code>. As before this can be done on
the console, but we will usually load packages as part of script.
<em>Note that we don’t need the quotes for the library function.</em></p>
<blockquote>
<p>Try installing the <code>cowsay</code> package and loading it. It has one function
called <code>say()</code> that you can use to create messages with animals.</p>
</blockquote>
</div>
<div id="functions-1" class="section level2">
<h2><span class="header-section-number">1.5</span> Using functions</h2>
<p>As stated in @ref(install-packages) a function is a piece of code written
to perform a specific task. Functions in R have the syntax of the name of the function
followed by round brackets. The round brackets are where we type the arguments
that the function requires to carry out its task. For example, in @ref(install-packages)
the function <code>install.packages()</code> requires the name of the package we want to
install as arguments.</p>
<p>Many, if not most, functions can take more than one argument. The creators of the
function should have given these defaults for the situation where the user provides
only one or some arguments. RStudio should prompt you for the arguments as you
type, but if you need to see what they are, use the help function <code>?</code> with the
function name in the Console and it will open the help panel or type the function
name into the help panel search box.</p>
<p>For example, to find out all the arguments for <code>install.packages()</code> we’d
type <code>?install.packages</code> and press <code>Enter</code>.</p>
<blockquote>
<p>Try using <code>say()</code> to say “I are programmer” in the <code>cowsay</code> package and then
find out what the arguments you can provide to make it produce different types of message.</p>
</blockquote>
</div>
<div id="getting-help" class="section level2">
<h2><span class="header-section-number">1.6</span> Getting help</h2>
<div id="using-to-access-r-function-help-pages" class="section level3">
<h3><span class="header-section-number">1.6.1</span> Using <code>?</code> to access R function help pages</h3>
<p>If you need help with a specific R function, let’s say <code>barplot()</code>, you can type
the function name without round brackets, with a question mark at the start:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1">?barplot</a></code></pre></div>
</div>
<div id="using-google-to-find-r-answers" class="section level3">
<h3><span class="header-section-number">1.6.2</span> Using Google to find R answers</h3>
<p>A Google or internet search “R &lt;task&gt;” will often either send you to the appropriate package documentation or a helpful forum question that someone else already asked,
such as the <a href="https://community.rstudio.com/">RStudio Community</a> or <a href="http://stackoverflow.com/questions/tagged/r">Stack Overflow</a>.</p>
</div>
<div id="asking-questions" class="section level3">
<h3><span class="header-section-number">1.6.3</span> Asking questions</h3>
<p>As well as knowing <a href="https://www.tidyverse.org/help/#where-to-ask">where to ask</a>, the key to get help
from someone is for them to grasp your problem rapidly. You
should make it as easy as possible to pinpoint where the issue might be.</p>
<p>Try to use the correct words to describe your problem. For instance, a
package is not the same thing as a library. Most people will understand
what you meant, but others have really strong feelings about the difference
in meaning. The key point is that it can make things confusing for people
trying to help you. Be as precise as possible when describing your problem.</p>
<p>If possible, try to reduce what doesn’t work to a simple <em>reproducible
example</em> otherwise known as a <em>reprex</em>.</p>
<p>For more information on how to write a reproducible example see
<a href="https://www.tidyverse.org/help/#reprex">this article</a> using the <code>reprex</code> package.</p>
</div>
</div>
<div id="workflow" class="section level2">
<h2><span class="header-section-number">1.7</span> A project orientated workflow</h2>
<p>This section is all about how to use R and RStudio to <strong>“maximize effectiveness and reduce frustration.”</strong></p>
<p>The above quote is from <a href="https://www.tidyverse.org/articles/2017/12/workflow-vs-script/">Jenny Bryan’s article</a>
about a project orientated workflow.</p>
<p>The main point here is that how you do things, <strong>the workflow</strong>, should not be
mixed up with the <strong>product of the workflow</strong> itself.</p>
<p>The product being:</p>
<ul>
<li>the raw data.</li>
<li>the code needed to produce the results from the raw data.</li>
</ul>
<p>Ways in which you can mix workflow and product include having lines in your script
that set your working directory, or using RStudio to save your environment when
you are working.</p>
<p><strong>But why is this a problem?</strong></p>
<p>It’s because <strong>your computer isn’t my computer</strong> or <strong>my laptop isn’t my desktop</strong>
or <strong>I’m now using a Windows machine and I wrote the code two years ago on a Mac</strong>.</p>
<p>By hard coding the directory into a script I have ensured my code will only run
on the machine in which it was written. Chances are you will want to share your
code with someone, either for publication or for them to check your work, or
because you are working collaboratively and therefore we need to avoid mixing
workflow with product.</p>
<p>Likewise we can’t share environments directly, but we can share the code that
creates the environment.</p>
<p>If we organise our analysis into self-contained projects that hold everything
needed to perform the analysis. These projects can be shared across machines and the analysis
recreated, and thus the workflow is kept separate from the product.</p>
<p>What does this look like in practice?</p>
<div id="rstudio-projects" class="section level3">
<h3><span class="header-section-number">1.7.1</span> RStudio Projects</h3>
<p>Step one is to use an interactive development environment such as RStudio rather
than using R on its own for your analysis.</p>
<p>RStudio contains a facility to keep all files associated with a particular
analysis together called, as you might expect from @ref(workflow), a Project.</p>
<p>Creating a Project creates a file <code>.Rproj</code> containing all the information associated
with your analysis including the Project location (allowing you to quickly navigate to it),
and optionally preserves custom settings and open files to make it easier to resume work after a
break. This is also super helpful if you are working on multiple projects as you can
switch between them at a click.</p>
<p>(ref:r-project) Creating a R project</p>
<div class="figure" style="text-align: center">
<img src="img/rstudio_create_project.PNG" alt="(ref:r-project)" width="80%" />
<p class="caption">
(#fig:r-projects)(ref:r-project)
</p>
</div>
<p>Below, we will go through the steps for creating an <code>Project</code>:</p>
<ul>
<li>Start R Studio (presentation of R Studio -below- should happen here)</li>
<li>Under the <code>File</code> menu, click on <code>New project</code>, choose <code>New directory</code>, then
<code>Empty project</code></li>
<li>Enter a name for this new folder (or “directory”, in computer science), and
choose a convenient location for it. This will be your <strong>working directory</strong>
for the rest of the day (e.g., <code>~/coding-together</code>)</li>
<li>Click on “Create project”</li>
<li>Under the <code>Files</code> tab on the right of the screen, click on <code>New Folder</code> and
create a folder named <code>data</code> within your newly created working directory. (e.g., <code>~/data</code>)</li>
<li>Create a R notebook (File &gt; New File &gt; R notebook) and save it in your working
directory (e.g. <code>01-coding-together-workshop-02-05-2019.Rmd</code>)</li>
<li>Or create a new R script (File &gt; New File &gt; R script) and save it in your working
directory (e.g. <code>01-coding-together-workshop-02-05-2019.R</code>)</li>
</ul>
</div>
<div id="r-notebooks-and-r-scripts" class="section level3">
<h3><span class="header-section-number">1.7.2</span> R notebooks and R scripts</h3>
<p><a href="https://bookdown.org/yihui/rmarkdown/notebook.html">R notebooks</a> combine writing
text with R code in chunks. The R code chunks are indicated by three backticks and
a lowercase r in brackets: <code>```{r} ```</code>. Text can be formatted using
<a href="https://bookdown.org/yihui/rmarkdown/markdown-syntax.html">markdown syntax</a>.
These are great for doing analysis
and report wrting at the same time.</p>
<p>R scripts are text files containing the commands that you would enter into the R
console. They are great for containing code you wish to call into another script
such as code for a function, or if you are submitting a script as job to run
on another computer without the need for RStudio.</p>
</div>
<div id="here" class="section level3">
<h3><span class="header-section-number">1.7.3</span> Level up with the <code>here</code> package</h3>
<p>This is a bit more tricky, so you might like to come back to <code>here</code> later, but
Jenny Bryan loves the <a href="https://here.r-lib.org/index.html"><code>here</code></a> package by
Kirill Müller so much <a href="https://github.com/jennybc/here_here">she wrote an ode to it</a>.</p>
<p>In a nutshell, the <code>here()</code> function sets the path implicitly to the top level of the R project
you are working in. <strong>But what does that mean, and why should I care?</strong></p>
<p>Using the <code>here()</code> function like this:</p>
<p><code>library(here)</code></p>
<p><code>here("data", "file_i_want.csv")</code></p>
<p>where <code>"data"</code> is the folder containing <code>"file_i_want.csv"</code>, the function works
out the rest of the path to the folder and file. This is useful if you open the
project on different machines where the path is different. <code>here()</code> takes care of
things, thus saving you some pain.</p>
</div>
<div id="names" class="section level3">
<h3><span class="header-section-number">1.7.4</span> Naming things</h3>
<p><a href="https://ropensci.org/blog/2017/12/08/rprofile-jenny-bryan/">Jenny Bryan</a>
also has three principles for <a href="http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf">naming things</a>
that are well worth remembering.</p>
<p>When you names something, a file or an object, ideally it should be:</p>
<ol style="list-style-type: decimal">
<li>Machine readable (no white space, punctuation, upper AND lower-case…)</li>
<li>Human readable (makes sense in 6 months or 2 years time)</li>
<li>Plays well with default ordering (numerical or date order)</li>
</ol>
<p>We’ll see examples of this as we go along.</p>
</div>
</div>
<div id="tidy-data" class="section level2">
<h2><span class="header-section-number">1.8</span> The tidyverse and tidy data</h2>
<p>The <a href="https://www.tidyverse.org/">tidyverse</a> <span class="citation">(Wickham <a href="#ref-R-tidyverse" role="doc-biblioref">2017</a>)</span> is <em>“an opinionated
collection of R packages designed for data science”</em> .</p>
<p>Tidyverse packages contain functions that <em>“share an underlying design
philosophy, grammar, and data structures.”</em> It’s this philosophy that makes
tidyverse functions and packages relatively easy to learn and use.</p>
<p>Tidy data follows three principals for tabular data as proposed in the Tidy Data
paper <a href="http://www.jstatsoft.org/v59/i10/paper" class="uri">http://www.jstatsoft.org/v59/i10/paper</a> :</p>
<ol style="list-style-type: decimal">
<li>Every variable has its own column.</li>
<li>Every observation has its own row.</li>
<li>Each value has its own cell.</li>
</ol>
<p>We’ll be using the tidyverse and learning more about tidy data as we go along.</p>
</div>
<div id="r-atoms" class="section level2">
<h2><span class="header-section-number">1.9</span> Atoms of R</h2>
<p>Having set ourselves up in RStudio, let’s turn our attention to the language of
R itself.</p>
<p>The basic building blocks of how R stores data are called atomic vector types.
It’s from these atoms that more complex structures are built. Atomic vectors
have one dimension, just like a single row or a single column in a spreadsheet.</p>
<p>The four main atoms of R are:</p>
<ul>
<li>Doubles: regular numbers, +ve or -ve and with or without decimal places. AKA numerics.</li>
<li>Integers: whole numbers, specified with an upper-case L, e.g. <code>int &lt;- 2L</code></li>
<li>Characters: Strings of text</li>
<li>Logicals: these store <code>TRUE</code>‘s and <code>FALSE</code>’s’ which are useful for comparisons.</li>
</ul>
<p>(ref:atomic-vectors) The four most used atomic vectors, the building blocks of R</p>
<div class="figure" style="text-align: center">
<img src="img/r-vectors-07-10-2018.png" alt="(ref:atomic-vectors)" width="50%" />
<p class="caption">
(#fig:atomic-vectors)(ref:atomic-vectors)
</p>
</div>
<p>Let’s make a character vector and check the atomic vector type, using the <code>typeof()</code>.
This also introduces a very important R function <code>c()</code>. This lower case c stands
for <strong>combine</strong>. So when we have several objects e.g. words or numbers, we can
combine them into a vector the length of the number of objects, as illustrated
here for a pack of cards:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1">cards &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;ace&quot;</span>, <span class="st">&quot;king&quot;</span>, <span class="st">&quot;queen&quot;</span>, <span class="st">&quot;jack&quot;</span>, <span class="st">&quot;ten&quot;</span>)</a>
<a class="sourceLine" id="cb3-2" title="2"></a>
<a class="sourceLine" id="cb3-3" title="3">cards</a></code></pre></div>
<pre><code>## [1] &quot;ace&quot;   &quot;king&quot;  &quot;queen&quot; &quot;jack&quot;  &quot;ten&quot;</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">typeof</span>(cards)</a></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Note here that we see the use of the assignment operator <code>&lt;-</code> to assign our
vector on the right as the object <code>cards</code>. We talk more about that in @ref(assignment).</p>
<blockquote>
<p>Try creating a vector of numbers from 1 to 10 using the seq() function. Remember
to use ?seq if you want to learn more about the function.</p>
</blockquote>
</div>
<div id="assignment" class="section level2">
<h2><span class="header-section-number">1.10</span> Assigning objects</h2>
<p>Objects are just a way to store data inside the R environment. We assign labels to
objects using the assignment operator <code>&lt;-</code></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">mass_kg &lt;-<span class="st"> </span><span class="dv">55</span></a></code></pre></div>
<p>Read this as <em>“mass_kg is assigned to value 55”</em> in your head. A subtle but important
point here is that the object is 55 and the value remains 55 regardless of the label we assign to it. In
fact we could assign more than one label to the same object. Another way to think
about this is that Bibi is a cat, and remains a cat even if I call her Princess when
she refuses to go out in the rain.</p>
<p>(ref:bibi-cat) Bibi remains a cat even if I call her Princess when she refuses to go out in the rain.</p>
<div class="figure" style="text-align: center">
<img src="img/bibi-data.png" alt="(ref:bibi-cat)" width="80%" />
<p class="caption">
(#fig:bibi-cat)(ref:bibi-cat)
</p>
</div>
<p>Using <code>&lt;-</code> can be annoying to type, so use RStudio’s keyboard short cut:
Alt + - (the minus sign) to make life easier.</p>
<p>Many people ask why we use this assignment operator when we can use <code>=</code> instead?</p>
<p><a href="https://twitter.com/_colinfay/status/1006139974377443328">Colin Fay had a Twitter thread on this subject</a>,
but the reason I favour most is that it provides clarity. The arrow points in
the direction of the assignment (it is actually possible to assign in the other
direction too) and it distinguishes between creating an object in the workspace
and assigning a value inside a function.</p>
<p>Object name style is a matter of choice, but must start with a letter and can
only contain letters, numbers, <code>_</code> and <code>.</code>. We recommend using descriptive names
and using <code>_</code> between words. Some special symbols cannot be used in variable
names, so watch out for those.</p>
<p>So here we’ve used the name to indicate its value represents a mass in kilograms.
Look in your environment pane and you’ll see the <code>mass_kg</code> object
containing the (data) value 55.</p>
<p>We can inspect an object by typing it’s name:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1">mass_kg</a></code></pre></div>
<pre><code>## [1] 55</code></pre>
<p>What’s wrong here?</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1">mass_KG</a></code></pre></div>
<p><code>Error: object 'mass_KG' not found</code></p>
<p>This error illustrates that typos matter, everything must be precise and <code>mass_KG</code>
is not the same as <code>mass_kg</code>. <code>mass_KG</code> doesn’t exist, hence the error.</p>
<p>Let’s use <code>seq()</code> to create a <strong>seq</strong>uence of numbers, and at the same time practice tab completion.</p>
<p>Start typing <code>se</code> in the console and you should see a list of functions appear,
add <code>q</code> to shorten the list, then use the up and down arrow to highlight the function
of interest <code>seq()</code> and hit Tab to select. This is tab completion.</p>
<p>RStudio puts the cursor between the parentheses to prompt us to enter some
arguments. Here we’ll use 1 as the start and 10 as the end:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">10</span>)</a></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<p>If we left off a parentheses to close the function, then when we hit enter
we’ll see a <code>+</code> indicating RStudio is expecting further code. We either add the
missing part or press Escape to cancel the code.</p>
<p>Let’s call a function and make an assignment at the same time. Here we’ll use
the base R function <code>seq()</code> which takes three arguments: <code>from</code>, <code>to</code> and <code>by</code>.</p>
<p>Read the following code as <em>"assign my_sequence to an object that stores a sequence of numbers from 2 to 20 by intervals of 2</em>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1">my_sequence &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">2</span>,<span class="dv">20</span>,<span class="dv">2</span>)</a></code></pre></div>
<p>This time nothing was returned to the console, but we now have an object called
<code>my_sequence</code> in our environment.</p>
<div id="indexing-and-subsetting" class="section level3">
<h3><span class="header-section-number">1.10.1</span> Indexing and subsetting</h3>
<p>If we want to access and subset elements of <code>my_sequence</code> we use
square brackets <code>[]</code> and the index number. Indexing in R starts at 1 such that
1 is the index of the first element in the sequence, element 1 having the the value of 2.</p>
<p>For example element five would be subset by:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1">my_sequence[<span class="dv">5</span>]</a></code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>Here the number five is the index of the vector, not the value of the fifth element. The value of the fifth element is 10.</p>
<p>And returning multiple elements uses a colon <code>:</code>, like so</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1">my_sequence[<span class="dv">5</span><span class="op">:</span><span class="dv">8</span>]</a></code></pre></div>
<pre><code>## [1] 10 12 14 16</code></pre>
</div>
</div>
<div id="lists-matrices-and-arrays" class="section level2">
<h2><span class="header-section-number">1.11</span> Lists, matrices and arrays</h2>
<p>Lists also group data into one dimensional sets of data. The difference being
that list group objects instead of individual values, such as several atomic
vectors.</p>
<p>For example, let’s make a list containing a vector of numbers and a character
vector</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1">list_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">110</span>,<span class="st">&quot;R&quot;</span>)</a>
<a class="sourceLine" id="cb18-2" title="2"></a>
<a class="sourceLine" id="cb18-3" title="3">list_<span class="dv">1</span></a></code></pre></div>
<pre><code>## [[1]]
##   [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
##  [18]  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34
##  [35]  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51
##  [52]  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
##  [69]  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
##  [86]  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102
## [103] 103 104 105 106 107 108 109 110
## 
## [[2]]
## [1] &quot;R&quot;</code></pre>
<p>Note the double brackets to indicate the list elements, i.e. element one is the
vector of numbers and element two is a vector of a single character.</p>
<p>We won’t be working with lists a great deal in these workshops, but they are a flexible way to
store data of different types in R.</p>
<p>Accessing list elements uses double square brackets syntax, for example
<code>list_1[[1]]</code> would return the first vector in our list.</p>
<p>And to access the first element in the first vector would combine double and
single square brackets like so: <code>list_1[[1]][1]</code>.</p>
<p>Don’t worry if you find this confusing, everyone does when they first start with
R. Hadley Wickham tweeted an image to illustrate list indexing shown in @ref(fig:list-index).</p>
<p>(ref:list-index) List indexing by Hadley Wickham</p>
<div class="figure">
<img src="img/indexing.png" alt="(ref:list-index)" width="100%" />
<p class="caption">
(#fig:list-index)(ref:list-index)
</p>
</div>
<p>Lists alongside <code>NULL</code> which indicates the absence of a vector, complete the set
of base vectors in R as illustrated in @ref(fig:base-vectors).</p>
<p>(ref:base-vectors) The base vectors in R.</p>
<div class="figure">
<img src="img/r-all-vectors-07-10-2018.png" alt="(ref:base-vectors)" width="60%" />
<p class="caption">
(#fig:base-vectors)(ref:base-vectors)
</p>
</div>
<div id="matrices-and-arrays" class="section level3">
<h3><span class="header-section-number">1.11.1</span> Matrices and arrays</h3>
<p>Matrices store values in a two dimensional array, whilst arrays can have n
dimensions. We won’t be using these either, but they are also valid R objects.</p>
</div>
</div>
<div id="factors" class="section level2">
<h2><span class="header-section-number">1.12</span> Factors</h2>
<p>Factors are Rs way of storing categorical information such as eye colour or
car type. A factor is something that can only have certain values, and can be
ordered (such as <code>low</code>,<code>medium</code>,<code>high</code>) or unordered such as types of fruit.</p>
<p>Factors are useful as they code string variables such as “red” or “blue” to integer
values e.g. 1 and 2, which can be used in statistical models and when plotting,
but they are confusing as they look like strings.</p>
<p><strong>Factors look like strings, but behave like integers.</strong></p>
<p>Historically R converts strings to factors when we load and create data, but
it’s often not what we want as a default. Fortunately, in the tidyverse strings
are not treated as factors by default.</p>
</div>
<div id="data-frames" class="section level2">
<h2><span class="header-section-number">1.13</span> Data frames</h2>
<p>For data analysis in R, we mostly be using data frames.</p>
<p>Data frames are two dimensional versions of lists, and this is form of storing
data we are going to be using. In a data frame each atomic vector type becomes
a column, and a data frame is formed by columns of vectors of the same length.
Each column element must be of the same type, but the column types can vary.</p>
<p>Figure @ref(fig:df) shows an example data frame we’ll refer to as
saved as the object <code>df</code> consisting of three rows and three columns. Each
column is a different atomic data type of the same length.</p>
<p>(ref:df) An example data frame <code>df</code>.</p>
<div class="figure" style="text-align: center">
<img src="img/data_frame.png" alt="(ref:df)" width="80%" />
<p class="caption">
(#fig:df)(ref:df)
</p>
</div>
<p>To create the data frame @ref(fig:df) we can use the <code>data.frame()</code> function
in conjunction with the <code>c()</code> function to make the individual atomic vectors
that comprise the data frame as follows. Note that I am naming the vectors as I make
the data frame after the type of vector e.g. <code>numeric_vector = c(1,7,3)</code>. Also,
as this is a base R function I need to tell the function not to treat the character
strings as categorical data using <code>stringsAsFactors = FALSE</code></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1">df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">numeric_vector =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">7</span>,<span class="dv">3</span>), </a>
<a class="sourceLine" id="cb20-2" title="2">                 <span class="dt">character_vector =</span> <span class="kw">c</span>(<span class="st">&quot;S&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;U&quot;</span>),</a>
<a class="sourceLine" id="cb20-3" title="3">                 <span class="dt">logical_vector =</span> <span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">FALSE</span>,<span class="ot">TRUE</span>), </a>
<a class="sourceLine" id="cb20-4" title="4">                 <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb20-5" title="5"></a>
<a class="sourceLine" id="cb20-6" title="6">df</a></code></pre></div>
<pre><code>##   numeric_vector character_vector logical_vector
## 1              1                S           TRUE
## 2              7                A          FALSE
## 3              3                U           TRUE</code></pre>
<p>Packages in the tidyverse create a modified form of data frame called a tibble.
You can read about tibbles <a href="http://r4ds.had.co.nz/tibbles.html">here</a>. One
advantage of tibbles is that they don’t default to treating strings as factors.
We deal with transforming data frames in chapters @ref(data-wrangle-1) and @ref(data-wrangle-2).</p>
<p>Here’s what the code to make the same data frame as before as a tibble looks like.
Note how we get more information from a tibble when it is returned to the Console,
it tells us what the dimensions are, and what type of vectors it contains.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1">df &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">numeric_vector =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">7</span>,<span class="dv">3</span>), </a>
<a class="sourceLine" id="cb22-2" title="2">                 <span class="dt">character_vector =</span> <span class="kw">c</span>(<span class="st">&quot;S&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;U&quot;</span>),</a>
<a class="sourceLine" id="cb22-3" title="3">                 <span class="dt">logical_vector =</span> <span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">FALSE</span>,<span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb22-4" title="4"></a>
<a class="sourceLine" id="cb22-5" title="5">df</a></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   numeric_vector character_vector logical_vector
##            &lt;dbl&gt; &lt;chr&gt;            &lt;lgl&gt;         
## 1              1 S                TRUE          
## 2              7 A                FALSE         
## 3              3 U                TRUE</code></pre>
<p>Sub-setting data frames can also be done with square bracket syntax, but as we
have both rows and columns, we need to provide index values for both row and
column.</p>
<p>For example <code>df[1,2]</code> means <strong>return the value of <code>df</code> row 1, column 2</strong>. This corresponds with the value <code>A</code>.</p>
<p>We can also use the colon operator to choose
several rows or columns, and by leaving the row or column blank we return all
rows or all columns.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1"><span class="co"># Subset rows 1 and 2 of column 1</span></a>
<a class="sourceLine" id="cb24-2" title="2">df[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb24-3" title="3"></a>
<a class="sourceLine" id="cb24-4" title="4"><span class="co"># Subset all rows of column 3</span></a>
<a class="sourceLine" id="cb24-5" title="5">df[,<span class="dv">3</span>]</a></code></pre></div>
<p>Don’t worry too much about this for now, we won’t be doing to much of this
in these lessons, but it’s worth being aware of this syntax.</p>
<div id="attributes" class="section level3">
<h3><span class="header-section-number">1.13.1</span> Attributes</h3>
<p>An attribute is a piece of information you can attach to an object, such as
names or dimensions. Attributes such as dimensions are added when
we create an object, but others such as names can be added.</p>
<p>Let’s look at the <code>mpg</code> data frame dimensions:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="co"># mpg has 234 rows (observations) and 11 columns (variables)</span></a>
<a class="sourceLine" id="cb25-2" title="2"><span class="kw">dim</span>(mpg)</a></code></pre></div>
<pre><code>## [1] 234  11</code></pre>
</div>
</div>
<div id="plotting-data" class="section level2">
<h2><span class="header-section-number">1.14</span> Plotting data</h2>
<p>One of the most useful and important parts of any data analysis is plotting
data. We’ll be spending a whole lesson on it in chapter @ref(viz), but to
give you an example, we’ll use the <code>ggplot2</code> package as an introduction to
automating a task in code, and as a tool for understanding data.</p>
<p><code>ggplot2</code> implements the <em>grammar of graphics</em>, for describing
and building graphs. The idea being that we construct a plot in the following way:</p>
<ol style="list-style-type: decimal">
<li>Call the <code>ggplot()</code> function to create a graph.</li>
<li>Pass our data as the first argue to the <code>ggplot()</code> function.</li>
<li>Then pass some arguments to the aesthetics function <code>aes()</code> inside
the <code>gpplot()</code> which tell ggplot how to plot the data e.g. which data goes on the x and y axis.</li>
<li>Then we follow the ggplot function with a <code>+</code> sign to indicate
we are going to add more code, followed by a geometric object function, a <code>geom</code>
which maps the data to type of plot we want to make e.g. a histogram or scatter plot.</li>
</ol>
<p>Don’t worry if this sounds confusing, it becomes clear with practice and all plots
follow this grammar.</p>
<p>We’ll use the <code>mpg</code> dataset that comes with the tidyverse to examine
the question <em>do cars with big engines use more fuel than cars with small engines?</em></p>
<p>Try <code>?mpg</code> to learn more about the data.</p>
<ol style="list-style-type: decimal">
<li>Engine size in litres is in the <code>displ</code> column.</li>
<li>Fuel efficiency on the highway in miles per gallon is given in the <code>hwy</code> column.</li>
</ol>
<p>To create a plot of engine size <code>displ</code> (x-axis) against fuel efficiency <code>hwy</code>
(y-axis) we do the following:</p>
<p>Now try extending this code to include to add a <code>colour</code> aesthetic to the
the <code>aes()</code> function, let <code>colour = class</code>, <code>class</code> being the vehicle type.
This should create a plot with as before but with the points coloured
according to the vehicle type to expand our understanding.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> mpg) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb27-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> displ, <span class="dt">y =</span> hwy, <span class="dt">colour =</span> class))</a></code></pre></div>
<p><img src="coding-together_files/figure-html/mpg-plot-2-1.png" width="672" /></p>
<p>Now we can see that as we might expect, bigger cars such as SUVs tend to have
bigger engines and are also less fuel efficient, but some smaller cars such as
2-seaters also have big engines and greater fuel efficiency. Hence we have a
more nuanced view with this additional aesthetic.</p>
<p>Check out the ggplot2 documentation for all the aesthetic possibilities (and
Google for examples): <a href="http://ggplot2.tidyverse.org/reference/" class="uri">http://ggplot2.tidyverse.org/reference/</a></p>
<p>So now we have re-usable code snippet for generating plots in R:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> <span class="op">&lt;</span>DATA<span class="op">&gt;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb28-2" title="2"><span class="st">  </span><span class="er">&lt;</span>GEOM_FUNCTION<span class="op">&gt;</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="op">&lt;</span>MAPPINGS<span class="op">&gt;</span>))</a></code></pre></div>
<p>Concretely, in our first example <code>&lt;DATA&gt;</code> was <code>mpg</code>, the <code>&lt;GEOM_FUNCTION&gt;</code>
was <code>geom_point()</code> and the arguments we supplies to map our aesthetics
<code>&lt;MAPPINGS&gt;</code> were <code>x = displ, y = hwy</code>.</p>
<p>As we can use this code for any tidy data set, hopefully you are beginning to
see how a small amount of code can do a lot.</p>
</div>
<div id="exporting-data" class="section level2">
<h2><span class="header-section-number">1.15</span> Exporting data</h2>
<p>We’ll spend more time on getting data in and out of our R environment in the
next chapter @ref(data-wrangle-2), but just to wrap this lesson up let’s imagine
we wanted to export our plot and data for a colleague or presentation.</p>
<div id="readr" class="section level3">
<h3><span class="header-section-number">1.15.1</span> readr</h3>
<p>To export tibbles and data frames, we’ll use the <code>readr</code> package, and the
<code>write_excel_csv()</code> function. This creates a table in comma separated variable
format that can opened by spreadsheet software such as excel.</p>
<p>As it is a function
is has round brackets and the main arguments we pass are the object containing
the data we want to output and the name of the file and the location we want to
write the file to.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1"><span class="kw">write_excel_csv</span>(df, <span class="st">&quot;outputs/example-data-02-05-2019.csv&quot;</span>)</a></code></pre></div>
<p>Here we are writing the <code>df</code> data frame as a csv file to the <code>outputs</code> folder
and a file called <code>example-data-02-05-2019.csv</code>.</p>
</div>
<div id="ggsave" class="section level3">
<h3><span class="header-section-number">1.15.2</span> ggsave</h3>
<p>If we want to save the last plot we made in <code>ggplot2</code> we can use the <a href="https://ggplot2.tidyverse.org/reference/ggsave.html"><code>ggsave()</code>
function</a></p>
<p>We tell <code>ggsave()</code> the filename, and it will save it as that type depending
on how we name the file. For example if we use <code>file.pdf</code> it will save a PDF and
if we use <code>file.jpeg</code> it will save a <code>jpeg</code>.</p>
<p>Check out <code>?ggsave</code> or the line above for more options.</p>
<p>To save our last plot for example:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="kw">ggsave</span>(<span class="st">&quot;outputs/example-plot-02-05-2019.pdf&quot;</span>)</a></code></pre></div>
</div>
<div id="exercise" class="section level3">
<h3><span class="header-section-number">1.15.3</span> Exercise</h3>
<blockquote>
<ol style="list-style-type: decimal">
<li>Create a new project called ‘coding-assessment-01’</li>
<li>Create two folders in this project: R and outputs</li>
<li>Create a R script using best naming practices i.e. name-date.R</li>
<li>In the script, write some comments at the top e.g. name, date, description</li>
<li>Create a tibble comprising of a character vector, a numeric vector</li>
<li>Install and load the <code>dslabs</code> package and create a density plot with ggplot2 using the
<code>heights</code> dataset, using the <code>x = height</code> variable and <code>fill = sex</code> to create a density plot
ggplot(data = heights, aes(x =height, fill = sex)) + geom_density()</li>
<li>Save the plot as pdf and the tibble as csv file to the output folder.</li>
</ol>
</blockquote>
<!--chapter:end:01-introduction.Rmd-->
</div>
</div>
</div>
<div id="data-wrangle-1" class="section level1">
<h1><span class="header-section-number">2</span> Data wrangling I</h1>
<p>By the end of this chapter you will:</p>
<ul>
<li>have learnt to load csv files</li>
<li>have used the key verbs of the <code>dplyr</code> package for transforming data to
arrange and filter observations, select variables, create new variables, and
create summaries.</li>
<li>have learnt how to combine functions with the pipe <code>%&gt;%</code> from the <code>magrittr</code> package
to combine tasks</li>
</ul>
<p>The following sections are based upon the <a href="https://r4ds.had.co.nz/transform.html">data transformation chapter</a> in R4DS and the
<a href="https://datacarpentry.org/R-ecology-lesson/index.html">Data Carpentry ecology lesson</a>.</p>
<div id="data-organisation-in-spreadsheets" class="section level2">
<h2><span class="header-section-number">2.1</span> Data organisation in spreadsheets</h2>
<p>Karl Broman and Kara Woo wrote as
paper all about <a href="https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989">Data Organization in Spreadsheets</a>.</p>
<p>It’s full of practical advice and context and well worth reading for helping
you think about best practices for organising your data for yourself, and when working with others.</p>
<div id="flat-formats-and-excel-files" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Flat formats and Excel files</h3>
<p>File formats like <code>.csv</code> and <code>.tsv</code>, comma separated variables and tab separated variables
respectively are plain text files. That is to
say they contain only the data, as text information, and are the simplest and most
convenient way to share data as most software can read and
interpret them.</p>
<p>Excel files saves files into its own proprietary format <code>.xls</code> or <code>.xlsx</code> that holds
information in addition to the data itself. For reading and
writing excel files in R, the tidyverse <code>readxl</code> package is very useful.</p>
</div>
</div>
<div id="portal-project" class="section level2">
<h2><span class="header-section-number">2.2</span> The Portal Project data</h2>
<p>In this chapter we are going to focus on data from the <a href="https://portal.weecology.org/">Portal Project</a>,
which is a long running survey of rodents and other species in the Chihuahuan Desert,
as analysed in the 1994 paper by Heske et. al:</p>
<p><strong>Long-Term Experimental Study of a Chihuahuan Desert Rodent Community: 13 Years
of Competition</strong>, DOI: 10.2307/1939547.</p>
<p><a href="https://www.biorxiv.org/content/10.1101/332783v1.full">A paper with details about the data and the project</a> is also available.</p>
<p>Specifically they explored the effect on the populations of small
seed eating rodents as a result of the exclusion of larger competitor kangaroo
rats over a period from 1977 to 1991.</p>
<p>We’ll also use some of their data to explore this question: <strong>What is the effect
of the exclusion of kangaroo rats from a plot of land on the granivore population?</strong></p>
<p>Figure @ref(fig:k-rat) shows an image of one of the species of kangaroo rats excluded during the
study.</p>
<p>(ref:krat) <a href="https://portalproject.wordpress.com/">Merriam’s kangaroo rat, Dipodomys merriami</a></p>
<div class="figure" style="text-align: center">
<img src="img/kratsep12.jpg" alt="(ref:krat)" width="100%" />
<p class="caption">
(#fig:k-rat)(ref:krat)
</p>
</div>
<p>Figure @ref(fig:fence) indicates how the exclusion works, where a for number of
fenced plots the kangaroo rats were either able to enter by a hole or kept out.</p>
<p>(ref:fence) Kangaroo Rat exclusion</p>
<div class="figure" style="text-align: center">
<img src="img/fence_hole.JPG" alt="(ref:fence)" width="60%" />
<p class="caption">
(#fig:fence)(ref:fence)
</p>
</div>
<p>The plots are 50 metres by 50 metres, and a survey of the species within each
plot has been ongoing once a month for many years.</p>
<p>The dataset is stored as a comma separated value (CSV) file.
Each row holds information for a single animal, and the columns represent:</p>
<table>
<thead>
<tr class="header">
<th>Column</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>record_id</td>
<td>Unique id for the observation</td>
<td>numeric</td>
</tr>
<tr class="even">
<td>month</td>
<td>month of observation</td>
<td>numeric</td>
</tr>
<tr class="odd">
<td>day</td>
<td>day of observation</td>
<td>numeric</td>
</tr>
<tr class="even">
<td>year</td>
<td>year of observation</td>
<td>numeric</td>
</tr>
<tr class="odd">
<td>plot_id</td>
<td>ID of a particular plot</td>
<td>numeric</td>
</tr>
<tr class="even">
<td>species_id</td>
<td>2-letter code</td>
<td>character</td>
</tr>
<tr class="odd">
<td>sex</td>
<td>sex of animal (“M”, “F”)</td>
<td>character</td>
</tr>
<tr class="even">
<td>hindfoot_length</td>
<td>length of the hindfoot in mm</td>
<td>numeric</td>
</tr>
<tr class="odd">
<td>weight</td>
<td>weight of the animal in grams</td>
<td>numeric</td>
</tr>
<tr class="even">
<td>genus</td>
<td>genus of animal</td>
<td>character</td>
</tr>
<tr class="odd">
<td>species</td>
<td>species of animal</td>
<td>character</td>
</tr>
<tr class="even">
<td>taxa</td>
<td>e.g. Rodent, Reptile, Bird, Rabbit</td>
<td>character</td>
</tr>
<tr class="odd">
<td>plot_type</td>
<td>type of plot</td>
<td>character</td>
</tr>
</tbody>
</table>
<p>The rodents species surveyed are:</p>
<p><strong>Kangaroo Rats</strong></p>
<table>
<thead>
<tr class="header">
<th>species_id</th>
<th>Scientific name</th>
<th>Common name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DM</td>
<td>Dipodomys merriami</td>
<td>Merriam’s kangaroo rat</td>
</tr>
<tr class="even">
<td>DO</td>
<td>Dipodomys ordii</td>
<td>Ord’s kangaroo rat</td>
</tr>
<tr class="odd">
<td>DS</td>
<td>Dipodomys spectabilis</td>
<td>Banner-tailed kangaroo rat</td>
</tr>
</tbody>
</table>
<p><strong>Granivores</strong></p>
<table>
<thead>
<tr class="header">
<th>species_id</th>
<th>Scientific name</th>
<th>Common name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PP</td>
<td>Chaetodipus penicillatus</td>
<td>Desert pocket mouse</td>
</tr>
<tr class="even">
<td>PF</td>
<td>Perognathus flavus</td>
<td>Silky pocket mouse</td>
</tr>
<tr class="odd">
<td>PE</td>
<td>Peromyscus eremicus</td>
<td>Cactus mouse</td>
</tr>
<tr class="even">
<td>PM</td>
<td>Peromyscus maniculatus</td>
<td>Deer Mouse</td>
</tr>
<tr class="odd">
<td>RM</td>
<td>Reithrodontomys megalotis</td>
<td>Western harvest mouse</td>
</tr>
</tbody>
</table>
<div id="downloading-and-importing-the-data" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Downloading and importing the data</h3>
<p><strong>First create a <a href="#workflow">R project</a> for this analysis e.g <code>coding-together-week-2</code></strong></p>
<p>The dataset is stored on-line, so we use the utility function
<code>download.file()</code> to download the csv file to our data folder.
(Did you create a data folder in the project directory?)</p>
<p>Here we pass the <code>url =</code> and <code>destfile =</code> arguments to <code>download.file()</code>.</p>
<p>As we have the <code>tidyverse</code> packages we can use the <code>readr</code> package it contains,
which has many functions for reading files, including <code>read_csv()</code>.
The advantage of <code>read_csv()</code> over base R <code>read.csv()</code> is that it defaults to reading strings as
character vectors rather than factors (categorical variables) which
is usually what we want.</p>
<p>As we read the data into our environment we need to assign a label
to the object we are creating. Here we assign the dataset to an object
called <code>surveys</code> using the <code>&lt;-</code> assignment operator.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="co"># Download the data</span></a>
<a class="sourceLine" id="cb31-2" title="2"><span class="kw">download.file</span>(<span class="dt">url=</span><span class="st">&quot;https://ndownloader.figshare.com/files/2292169&quot;</span>,</a>
<a class="sourceLine" id="cb31-3" title="3">              <span class="dt">destfile =</span> <span class="st">&quot;data/portal_data_joined.csv&quot;</span>)</a>
<a class="sourceLine" id="cb31-4" title="4"></a>
<a class="sourceLine" id="cb31-5" title="5"><span class="co"># Read into R as an object called surveys</span></a>
<a class="sourceLine" id="cb31-6" title="6">surveys &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/portal_data_joined.csv&quot;</span>)</a></code></pre></div>
</div>
</div>
<div id="dplyr" class="section level2">
<h2><span class="header-section-number">2.3</span> <code>dplyr</code></h2>
<p><a href="https://dplyr.tidyverse.org/"><code>dplyr</code></a> <em>“is a grammar of data manipulation”</em>.
Concretely, it’s a package of functions from the tidyverse that have been
created for tasks that require manipulation of data stored in <a href="data-frames">data frames</a>.</p>
<div class="figure" style="text-align: center">
<img src="img/dplyr-name-github.png" alt="[Why is it called `dplyr`?](https://github.com/tidyverse/dplyr/issues/1857)" width="100%" />
<p class="caption">
(#fig:dplyr-name)<a href="https://github.com/tidyverse/dplyr/issues/1857">Why is it called <code>dplyr</code>?</a>
</p>
</div>
<p>We’re going to use the most common verbs in <code>dplyr</code> to examine the Portal Project
surveys data.</p>
<div id="filter-rows-with-filter" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Filter rows with <code>filter()</code></h3>
<p>The first verb to consider is the <code>filter()</code> function which enables us to subset observations
based on their value.</p>
<p>Consider the surveys data and sub-setting observations that only occurred from
1985 onwards. It’s fairly natural to say <em>“filter the survey where the year
variable is equal or greater than 1985”</em>. And indeed this is how we use <code>filter()</code>
as a verb.</p>
<p>Figure @ref(fig:dplyr-filter) shows how
we give the filter function two arguments. The first is the
data frame, the second is the variable and condition on which we wish to filter.</p>
<p>An alternative way to use <code>filter()</code> is to “pipe” the function using pipe <code>%&gt;%</code> from the <code>magrittr</code> package
which you can think of as using the word <em>“then”</em>. We take our data set <em>then</em> filter it.
Using the pipe makes more sense when combining several operations.</p>
<blockquote>
<p>Ctl+Shift+M is a keyboard short cut to create a pipe.</p>
</blockquote>
<p>For the filter itself, from R4DS:</p>
<p><em>“To use filtering effectively, you have to know how to select the observations t
hat you want using the comparison operators. R provides the standard suite: <code>&gt;</code>,
<code>&gt;=</code>, <code>&lt;</code>, <code>&lt;=</code>, <code>!=</code> (not equal), and <code>==</code> (equal)….For other types of combinations,
you’ll need to use Boolean operators yourself: <code>&amp;</code> is “and”, <code>|</code> is “or”, and <code>!</code> is “not”."</em></p>
<p>See <a href="https://r4ds.had.co.nz/transform.html#fig:bool-ops">Figure 5.1</a> in R4DS for
to see how these operators work.</p>
<p>(Note that we aren’t assigning the output to an object here, so we can see it.)</p>
<p>(ref:filter) <code>dplyr::filter()</code></p>
<div class="figure" style="text-align: center">
<img src="img/dplyr_filter.png" alt="(ref:filter)" width="100%" />
<p class="caption">
(#fig:dplyr-filter)(ref:filter)
</p>
</div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1"><span class="co"># Filter observations that only occurred from 1985 onwards</span></a>
<a class="sourceLine" id="cb32-2" title="2"> <span class="kw">filter</span>(surveys, year <span class="op">&gt;=</span><span class="st"> </span><span class="dv">1985</span>)</a></code></pre></div>
<pre><code>## # A tibble: 25,290 x 13
##    record_id month   day  year plot_id species_id sex   hindfoot_length
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;
##  1     10606     7    24  1985       2 NL         F                  30
##  2     10617     7    24  1985       2 NL         M                  32
##  3     10627     7    24  1985       2 NL         F                  32
##  4     10720     8    20  1985       2 NL         F                  31
##  5     10923    10    13  1985       2 NL         F                  31
##  6     10949    10    13  1985       2 NL         F                  33
##  7     11215    12     8  1985       2 NL         F                  32
##  8     11329     3     9  1986       2 NL         M                  34
##  9     11496     5    11  1986       2 NL         F                  31
## 10     11498     5    11  1986       2 NL         F                  31
## # ... with 25,280 more rows, and 5 more variables: weight &lt;dbl&gt;,
## #   genus &lt;chr&gt;, species &lt;chr&gt;, taxa &lt;chr&gt;, plot_type &lt;chr&gt;</code></pre>
<p>An example using Boolean logic, would be to use the “or” operator <code>|</code> to filter
for the observations only occurring on <code>plot_type</code>’s control or long term kangaroo
rat exclusion. This time we assign the output to a new data frame called <code>surveys_filtered</code>.</p>
<p><strong>Note:</strong> as <code>plot_type</code> is a character vector we put the terms in quotes,
and also the double equals sign <code>==</code> “for equal to”.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1"><span class="co"># Keep only the rows corresponding with the Control and Long-term Krat Exclosure</span></a>
<a class="sourceLine" id="cb34-2" title="2">surveys_filtered &lt;-<span class="st"> </span>surveys <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb34-3" title="3"><span class="st">        </span><span class="kw">filter</span>(plot_type <span class="op">==</span><span class="st"> &quot;Control&quot;</span> <span class="op">|</span><span class="st"> </span>plot_type <span class="op">==</span><span class="st"> &quot;Long-term Krat Exclosure&quot;</span>)</a></code></pre></div>
<p><strong>Note:</strong> <code>filter()</code> only includes rows where the condition is TRUE; it excludes both <code>FALSE</code> and missing <code>NA</code> values.
We have to explicitly ask to keep <code>NA</code> values using <code>is.na()</code> as an additional filter.</p>
<blockquote>
<p>How did I know which <code>plot_type</code>’s to filter?
I used the <code>dplyr::distinct()</code> function, passing the <code>surveys</code> data frame
and the <code>plot_type</code> variable to obtain a list of the unique plot types,
from which I determined the <code>Control</code> and <code>Long-term Krat Exclosure</code> plots
were the ones I was after. Note that you need to add the argument
<code>.keep_all = TRUE</code> to <code>distinct()</code> to return all the columns in the
data frame</p>
</blockquote>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1"><span class="kw">distinct</span>(surveys, plot_type)</a></code></pre></div>
<pre><code>## # A tibble: 5 x 1
##   plot_type                
##   &lt;chr&gt;                    
## 1 Control                  
## 2 Long-term Krat Exclosure 
## 3 Short-term Krat Exclosure
## 4 Rodent Exclosure         
## 5 Spectab exclosure</code></pre>
</div>
<div id="arrange-rows-with-arrange" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Arrange rows with <code>arrange()</code></h3>
<p>The next verb is <code>arrange()</code> which also operates on the rows, and enables
you to arrange the observations in a data frame according to one or more variables.</p>
<p>As with <code>filter()</code> we supply the variable or variables of interest as the arguments
to <code>arrange()</code>.</p>
<p>From <a href="https://r4ds.had.co.nz/transform.html#arrange-rows-with-arrange">R4DS</a>:</p>
<p><em>“If you provide more than one column name, each additional column will be used to
break ties in the values of preceding columns…
Missing values are always sorted at the end.”</em></p>
<p>Figure @ref(fig:dplyr-arrange) shows how to arrange the observations according to the <code>record_id</code>
variable.</p>
<p>(ref:arrange) <code>dplyr::arrange()</code></p>
<div class="figure" style="text-align: center">
<img src="img/dplyr_arrange.png" alt="(ref:arrange)" width="100%" />
<p class="caption">
(#fig:dplyr-arrange)(ref:arrange)
</p>
</div>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1">surveys <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(record_id)</a></code></pre></div>
<pre><code>## # A tibble: 34,786 x 13
##    record_id month   day  year plot_id species_id sex   hindfoot_length
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;
##  1         1     7    16  1977       2 NL         M                  32
##  2         2     7    16  1977       3 NL         M                  33
##  3         3     7    16  1977       2 DM         F                  37
##  4         4     7    16  1977       7 DM         M                  36
##  5         5     7    16  1977       3 DM         M                  35
##  6         6     7    16  1977       1 PF         M                  14
##  7         7     7    16  1977       2 PE         F                  NA
##  8         8     7    16  1977       1 DM         M                  37
##  9         9     7    16  1977       1 DM         F                  34
## 10        10     7    16  1977       6 PF         F                  20
## # ... with 34,776 more rows, and 5 more variables: weight &lt;dbl&gt;,
## #   genus &lt;chr&gt;, species &lt;chr&gt;, taxa &lt;chr&gt;, plot_type &lt;chr&gt;</code></pre>
<p>Or we could use <code>arrange()</code> to find the record with the shortest hindfoot.
<em>Note:</em> <code>arrange()</code> defaults to ascending order.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1">surveys <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(hindfoot_length)</a></code></pre></div>
<pre><code>## # A tibble: 34,786 x 13
##    record_id month   day  year plot_id species_id sex   hindfoot_length
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;
##  1     31400     9    30  2000      19 PB         M                   2
##  2     10067     3    16  1985      19 RM         M                   6
##  3     19567     1     8  1992      19 BA         M                   6
##  4     19015     9     9  1991      19 BA         F                   7
##  5     21036     8    19  1993      21 PF         F                   7
##  6     31457     9    31  2000       6 RM         M                   8
##  7     19191    10    11  1991      13 PF         F                   8
##  8      5801     4    29  1982       7 RM         &lt;NA&gt;                8
##  9     33647     3    14  2002       3 PF         M                   9
## 10     20562    12    22  1992       5 RM         F                   9
## # ... with 34,776 more rows, and 5 more variables: weight &lt;dbl&gt;,
## #   genus &lt;chr&gt;, species &lt;chr&gt;, taxa &lt;chr&gt;, plot_type &lt;chr&gt;</code></pre>
<p>To find the Cactus Mouse, (<code>species_id == "PE"</code>) with the longest hindfoot we combine
<code>filter()</code> with <code>arrangee()</code> using the pipe:</p>
<p><em>Hint</em> Use the <code>desc()</code> function to arrange from biggest to smallest.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1">surveys <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb41-2" title="2"><span class="st">        </span><span class="kw">filter</span>(species_id <span class="op">==</span><span class="st"> &quot;PE&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb41-3" title="3"><span class="st">        </span><span class="kw">arrange</span>(<span class="kw">desc</span>(hindfoot_length))</a></code></pre></div>
<pre><code>## # A tibble: 1,299 x 13
##    record_id month   day  year plot_id species_id sex   hindfoot_length
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;
##  1      1202     9     3  1978       7 PE         F                  30
##  2       517     1     8  1978       2 PE         M                  26
##  3     32443     8    25  2001      23 PE         F                  24
##  4      5080    12    30  1981      15 PE         F                  23
##  5      5090    12    30  1981      15 PE         F                  23
##  6     33700     3    14  2002       9 PE         F                  23
##  7       604     2    18  1978       2 PE         M                  22
##  8     12459     3     2  1987       2 PE         F                  22
##  9     13992     1    24  1988       2 PE         M                  22
## 10     14516     5    15  1988       2 PE         F                  22
## # ... with 1,289 more rows, and 5 more variables: weight &lt;dbl&gt;,
## #   genus &lt;chr&gt;, species &lt;chr&gt;, taxa &lt;chr&gt;, plot_type &lt;chr&gt;</code></pre>
</div>
<div id="select-columns-with-select" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Select columns with <code>select()</code></h3>
<p>Often your data contains variables you don’t need for the analysis you are performing, or you want to subset them to share with others.
To select only the ones you need, or explore subsets of the variables, the
<code>select()</code> verb enables you to keep only the columns of interest.</p>
<p>Figure @ref(fig:dplyr-select) shows the use of <code>select()</code> to choose only
the <code>year</code> and <code>plot_type</code> columns, with or without the pipe.</p>
<p>Selecting the variables contained in the columns can be done in various ways.
For example, by the column number, the variable name or by range.
Check the help function <code>?select</code> for more options.</p>
<p>(ref:select) <code>dplyr::select()</code></p>
<div class="figure" style="text-align: center">
<img src="img/dplyr_select.png" alt="(ref:select)" width="100%" />
<p class="caption">
(#fig:dplyr-select)(ref:select)
</p>
</div>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="co"># Select the year and plot type columns</span></a>
<a class="sourceLine" id="cb43-2" title="2">surveys <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(year,plot_type)</a></code></pre></div>
<pre><code>## # A tibble: 34,786 x 2
##     year plot_type
##    &lt;dbl&gt; &lt;chr&gt;    
##  1  1977 Control  
##  2  1977 Control  
##  3  1977 Control  
##  4  1977 Control  
##  5  1977 Control  
##  6  1977 Control  
##  7  1977 Control  
##  8  1978 Control  
##  9  1978 Control  
## 10  1978 Control  
## # ... with 34,776 more rows</code></pre>
<p>We can also use negative selection by adding a minus sign <code>-</code> to variables we
wish to discard. Here we discard <code>sex</code>,<code>hindfoot_length</code> and <code>weight</code> from the
<code>surveys_filtered</code> object and keep everything else:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="co"># Select everything except sex, hindfoot and weight</span></a>
<a class="sourceLine" id="cb45-2" title="2">surveys_filtered <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>sex,<span class="op">-</span>hindfoot_length,<span class="op">-</span>weight)</a></code></pre></div>
<pre><code>## # A tibble: 20,729 x 10
##    record_id month   day  year plot_id species_id genus species taxa 
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;
##  1         1     7    16  1977       2 NL         Neot~ albigu~ Rode~
##  2        72     8    19  1977       2 NL         Neot~ albigu~ Rode~
##  3       224     9    13  1977       2 NL         Neot~ albigu~ Rode~
##  4       266    10    16  1977       2 NL         Neot~ albigu~ Rode~
##  5       349    11    12  1977       2 NL         Neot~ albigu~ Rode~
##  6       363    11    12  1977       2 NL         Neot~ albigu~ Rode~
##  7       435    12    10  1977       2 NL         Neot~ albigu~ Rode~
##  8       506     1     8  1978       2 NL         Neot~ albigu~ Rode~
##  9       588     2    18  1978       2 NL         Neot~ albigu~ Rode~
## 10       661     3    11  1978       2 NL         Neot~ albigu~ Rode~
## # ... with 20,719 more rows, and 1 more variable: plot_type &lt;chr&gt;</code></pre>
</div>
<div id="create-new-variables-with-mutate" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Create new variables with <code>mutate()</code></h3>
<p>Another common task is to create a new variable or variables, often from existing data
within the data frame. For this we use the <code>mutate()</code> verb. It follows the
same syntax as for <code>filter()</code>, <code>arrange()</code> and <code>select()</code> in that the first
argument is the dataset, and the subsequent arguments are the new variables we wish
to create.</p>
<p>Figure @ref(fig:dplyr-mutate) shows how to create a new variable <code>weight_kg</code> by
dividing the existing <code>weight</code> variable in grams by 1000.</p>
<p>(ref:mutate) <code>dplyr::mutate()</code></p>
<div class="figure" style="text-align: center">
<img src="img/dplyr-mutate-16-10-2019.png" alt="(ref:mutate)" width="100%" />
<p class="caption">
(#fig:dplyr-mutate)(ref:mutate)
</p>
</div>
<p>A more complicated mutation, and key to to our analysis exploring the question
as to whether Kangaroo rats effect the size of the granivore population would
be to create a variable that indicates which type of rodent an observation is
recording.</p>
<p>To do this we can make use of another <code>dplyr</code> function called <code>case_when()</code>.
This allows us to pass different values to our new <code>rodent_type</code> variable <strong>if</strong>
they match either <code>species_id</code> values corresponding with Kangaroo rats or Granivores.</p>
<p>To remind us, the rodents species surveyed are:</p>
<p><strong>Kangaroo Rats</strong></p>
<table>
<thead>
<tr class="header">
<th>species_id</th>
<th>Scientific name</th>
<th>Common name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DM</td>
<td>Dipodomys merriami</td>
<td>Merriam’s kangaroo rat</td>
</tr>
<tr class="even">
<td>DO</td>
<td>Dipodomys ordii</td>
<td>Ord’s kangaroo rat</td>
</tr>
<tr class="odd">
<td>DS</td>
<td>Dipodomys spectabilis</td>
<td>Banner-tailed kangaroo rat</td>
</tr>
</tbody>
</table>
<p><strong>Granivores</strong></p>
<table>
<thead>
<tr class="header">
<th>species_id</th>
<th>Scientific name</th>
<th>Common name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PP</td>
<td>Chaetodipus penicillatus</td>
<td>Desert pocket mouse</td>
</tr>
<tr class="even">
<td>PF</td>
<td>Perognathus flavus</td>
<td>Silky pocket mouse</td>
</tr>
<tr class="odd">
<td>PE</td>
<td>Peromyscus eremicus</td>
<td>Cactus mouse</td>
</tr>
<tr class="even">
<td>PM</td>
<td>Peromyscus maniculatus</td>
<td>Deer Mouse</td>
</tr>
<tr class="odd">
<td>RM</td>
<td>Reithrodontomys megalotis</td>
<td>Western harvest mouse</td>
</tr>
</tbody>
</table>
<p>The first argument to <code>case_when()</code> is the variable and value we want to match,
just like <code>filter()</code>, for example <code>species_id == "DM"</code>, and then we use the tilde
operator <code>~</code> followed by the value we want give our new variable <strong>if</strong> a we match
this condition. Here we want our new variable <code>rodent_type</code> to be “Kangaroo Rat”.</p>
<p>We do this for every case we want to match. There are other species than rodents
in this data, and we have choice to either provide values for each one, ignore them
which will lead to the value <code>NA</code> for those rows or we can supply a single value
to the rest by giving the argument <code>TRUE</code> followed by the value. This means if
there are other values in <code>species_id</code> - if this is true - then give them all the
same value. Here we supply the value “Other” for the remaining species: <code>TRUE ~ "Other"</code>.</p>
<p>Below is how this looks in practice and is assigned to a new <code>surveys_mutated</code> object.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="co"># Mutate surveys_filtered</span></a>
<a class="sourceLine" id="cb47-2" title="2">surveys_mutated &lt;-<span class="st"> </span>surveys_filtered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb47-3" title="3"><span class="st">  </span><span class="co"># Create rodent type variable for K-rats and Granivores.Everything else, Other.</span></a>
<a class="sourceLine" id="cb47-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">rodent_type =</span> <span class="kw">case_when</span>(</a>
<a class="sourceLine" id="cb47-5" title="5">         species_id <span class="op">==</span><span class="st"> &quot;DM&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb47-6" title="6">         species_id <span class="op">==</span><span class="st"> &quot;DO&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb47-7" title="7">         species_id <span class="op">==</span><span class="st"> &quot;DS&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb47-8" title="8">         species_id <span class="op">==</span><span class="st"> &quot;PP&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb47-9" title="9">         species_id <span class="op">==</span><span class="st"> &quot;PF&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb47-10" title="10">         species_id <span class="op">==</span><span class="st"> &quot;PE&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb47-11" title="11">         species_id <span class="op">==</span><span class="st"> &quot;PM&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb47-12" title="12">         species_id <span class="op">==</span><span class="st"> &quot;RM&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb47-13" title="13">         <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;Other&quot;</span>))</a>
<a class="sourceLine" id="cb47-14" title="14"></a>
<a class="sourceLine" id="cb47-15" title="15"><span class="co"># Check output using distinct()</span></a>
<a class="sourceLine" id="cb47-16" title="16">surveys_mutated <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(species_id,rodent_type) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb47-17" title="17"><span class="st">        </span><span class="kw">distinct</span>(species_id, <span class="dt">.keep_all =</span> T)</a></code></pre></div>
<pre><code>## # A tibble: 42 x 2
##    species_id rodent_type 
##    &lt;chr&gt;      &lt;chr&gt;       
##  1 NL         Other       
##  2 DM         Kangaroo Rat
##  3 PF         Granivore   
##  4 PE         Granivore   
##  5 DS         Kangaroo Rat
##  6 PP         Granivore   
##  7 SH         Other       
##  8 OT         Other       
##  9 DO         Kangaroo Rat
## 10 OX         Other       
## # ... with 32 more rows</code></pre>
</div>
<div id="grouped-summaries-with-group_by-and-summarise" class="section level3">
<h3><span class="header-section-number">2.3.5</span> Grouped summaries with <code>group_by()</code> and <code>summarise()</code></h3>
<p>Finally we’ll look at the verb <code>summarise()</code> and it’s companion <code>group_by()</code>.</p>
<p><code>summarise()</code> collapses a data frame
into a single row. For example as shown in Figure @ref(fig:dplyr-summarise), we
could use it to find the average weight
of all the animals surveyed in the original data frame using <code>mean()</code>. (Here the
<code>na.rm = TRUE</code> argument is given to remove missing values from the data,
otherwise R would return <code>NA</code> when trying to average.)</p>
<p>(ref:summarise) <code>dplyr::summarise()</code></p>
<p>(ref:group-by) <code>dplyr::group_by()</code></p>
<div class="figure" style="text-align: center">
<img src="img/dplyr-summarise-16-10-2019.png" alt="(ref:summarise)" width="100%" />
<p class="caption">
(#fig:dplyr-summarise)(ref:summarise)
</p>
</div>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1">surveys <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb49-2" title="2"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_weight =</span> <span class="kw">mean</span>(weight, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   mean_weight
##         &lt;dbl&gt;
## 1        42.7</code></pre>
<p>However <code>summarise()</code> is most useful when paired with <code>group_by()</code>
which defines the variables upon which we operate upon.</p>
<p>Figure @ref(fig:group-by) shows how by grouping the observations according to the
<code>sex</code> and <code>species_id</code> variables, we can then calculate the <code>mean_weight</code> for
each of these groups.</p>
<div class="figure" style="text-align: center">
<img src="img/dplyr-group-by-16-10-2019.png" alt="(ref:group-by)" width="100%" />
<p class="caption">
(#fig:group-by)(ref:group-by)
</p>
</div>
<p>Using <code>group_by()</code> with <code>summarise()</code> now returns a table with 92 rows instead of single row.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1">surveys <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb51-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(sex, species_id) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb51-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_weight =</span> <span class="kw">mean</span>(weight, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</a></code></pre></div>
<pre><code>## # A tibble: 92 x 3
## # Groups:   sex [3]
##    sex   species_id mean_weight
##    &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;
##  1 F     BA                9.16
##  2 F     DM               41.6 
##  3 F     DO               48.5 
##  4 F     DS              118.  
##  5 F     NL              154.  
##  6 F     OL               31.1 
##  7 F     OT               24.8 
##  8 F     OX               21   
##  9 F     PB               30.2 
## 10 F     PE               22.8 
## # ... with 82 more rows</code></pre>
</div>
</div>
<div id="using-dpylr-to-explore-the-effect-of-kangaroo-rat-exclusion-on-granivore-populations" class="section level2">
<h2><span class="header-section-number">2.4</span> Using <code>dpylr</code> to explore the effect of Kangaroo Rat exclusion on Granivore populations</h2>
<p>Let’s use what we’ve learnt so far to explore the effect of Kangaroo Rats on Granivore populations
for the entire time covered in the <code>surveys</code> dataset.</p>
<p>A line plot with time on the x-axis and number of rodents on the y-axis would be
one way to visual this, comparing the observations between the control plots and the Kangaroo
rat exclusion plots.</p>
<p>One way to do this is to:</p>
<ol style="list-style-type: decimal">
<li><code>filter()</code> the observations for the control and exclusion plots.</li>
<li>Create a new <code>rodent_type</code> variable for Kangaroo Rats and Granivores.</li>
<li>Create a new variable for time from the existing <code>day</code>,<code>month</code> and <code>year</code> variables.</li>
<li>Group the data according to the <code>rodent_type</code>, <code>plot_type</code> our time variable, and use <code>summarise()</code> to calculate the number of observations for each group.</li>
</ol>
<div id="re-cap-of-filter-and-mutate" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Re-cap of <code>filter()</code> and <code>mutate()</code></h3>
<p>Let’s re-cap steps one and two:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="co"># Keep only the rows corresponding with the Control and Long-term Krat Exclosure</span></a>
<a class="sourceLine" id="cb53-2" title="2">surveys_filtered &lt;-<span class="st"> </span>surveys <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb53-3" title="3"><span class="st">        </span><span class="kw">filter</span>(plot_type <span class="op">==</span><span class="st"> &quot;Control&quot;</span> <span class="op">|</span><span class="st"> </span>plot_type <span class="op">==</span><span class="st"> &quot;Long-term Krat Exclosure&quot;</span>)</a>
<a class="sourceLine" id="cb53-4" title="4"></a>
<a class="sourceLine" id="cb53-5" title="5"><span class="co"># Mutate surveys_filtered</span></a>
<a class="sourceLine" id="cb53-6" title="6">surveys_mutated &lt;-<span class="st"> </span>surveys_filtered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb53-7" title="7"><span class="st">  </span><span class="co"># Create rodent type variable for K-rats and Granivores.Everything else, Other.</span></a>
<a class="sourceLine" id="cb53-8" title="8"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">rodent_type =</span> <span class="kw">case_when</span>(</a>
<a class="sourceLine" id="cb53-9" title="9">         species_id <span class="op">==</span><span class="st"> &quot;DM&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb53-10" title="10">         species_id <span class="op">==</span><span class="st"> &quot;DO&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb53-11" title="11">         species_id <span class="op">==</span><span class="st"> &quot;DS&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb53-12" title="12">         species_id <span class="op">==</span><span class="st"> &quot;PP&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb53-13" title="13">         species_id <span class="op">==</span><span class="st"> &quot;PF&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb53-14" title="14">         species_id <span class="op">==</span><span class="st"> &quot;PE&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb53-15" title="15">         species_id <span class="op">==</span><span class="st"> &quot;PM&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb53-16" title="16">         species_id <span class="op">==</span><span class="st"> &quot;RM&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb53-17" title="17">         <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;Other&quot;</span>))</a></code></pre></div>
</div>
<div id="use-lubridate-to-create-new-time-variables" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Use <code>lubridate</code> to create new time variables</h3>
<p>Step three introduces the tidyverse <a href="https://lubridate.tidyverse.org/"><code>lubridate</code> package</a>.
As the name suggests, this is a package for wrangling dates and times.</p>
<p>It would be clearer to plot the data on three month (quarterly) basis rather than
plotting every date in the dataset, so we need to create a variable that contains
the quarter in which the observation was made, for each observation.</p>
<p>From <code>lubridate</code> we will use the function <code>make_date()</code> in combination with <code>mutate()</code>
first to create a single column <code>date</code> variable from the <code>day</code>,<code>month</code> and <code>year</code> variables.
We then use this <code>date</code> variable to create another new variable containing a value for the
quarter of the year in which the observation was made <code>quarter</code> using the <code>quarter()</code> function.</p>
<p>We’ll assign this output to a new data frame called <code>surveys_subset</code>.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1"><span class="kw">library</span>(lubridate)</a>
<a class="sourceLine" id="cb54-2" title="2">surveys_subset &lt;-<span class="st"> </span>surveys_mutated <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb54-3" title="3"><span class="st">        </span><span class="kw">mutate</span>(<span class="dt">date =</span> <span class="kw">make_date</span>(<span class="dt">day =</span> day, <span class="dt">month =</span> month, <span class="dt">year =</span> year), </a>
<a class="sourceLine" id="cb54-4" title="4">               <span class="dt">quarter =</span> <span class="kw">quarter</span>(date,<span class="dt">with_year =</span> <span class="ot">TRUE</span>))</a></code></pre></div>
</div>
<div id="group-and-summarise-the-data-into-quarterly-observations" class="section level3">
<h3><span class="header-section-number">2.4.3</span> Group and summarise the data into quarterly observations</h3>
<p>Step four is to group and summarise our quarterly observations.</p>
<p>We group by <code>rodent_type</code>, <code>plot_type</code> and
<code>quarter</code> variables. In other words we’ve grouped the data according to Kangaroo Rat or
Granivore, Control plot or Exclusion plot, and the quarter of the year in which
the observation occurred.</p>
<p>Then we can calculate the number of captures for each of these groups by
using <code>summarise()</code> to create a <code>mean_captures</code> variable which is equal to the number
of rows for that group using the <code>n()</code> function divided by 4 to calculate
the average over each quarter.</p>
<p><strong>Note:</strong> <code>n()</code> is a <code>dplyr</code> function that returns the number of observations in the current group.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1">by_quarter &lt;-<span class="st"> </span>surveys_subset <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb55-2" title="2"><span class="st">        </span><span class="kw">group_by</span>(rodent_type,plot_type,quarter) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb55-3" title="3"><span class="st">        </span><span class="kw">summarise</span>(<span class="dt">mean_captures =</span> <span class="kw">n</span>()<span class="op">/</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb55-4" title="4"></a>
<a class="sourceLine" id="cb55-5" title="5">by_quarter</a></code></pre></div>
<pre><code>## # A tibble: 567 x 4
## # Groups:   rodent_type, plot_type [6]
##    rodent_type plot_type quarter mean_captures
##    &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt;         &lt;dbl&gt;
##  1 Granivore   Control     1977.          3.75
##  2 Granivore   Control     1977.          2   
##  3 Granivore   Control     1978.          2.75
##  4 Granivore   Control     1978.          2.25
##  5 Granivore   Control     1978.          3.25
##  6 Granivore   Control     1978.          1   
##  7 Granivore   Control     1979.          1.25
##  8 Granivore   Control     1979.          1.5 
##  9 Granivore   Control     1979.          1.25
## 10 Granivore   Control     1980.          5.5 
## # ... with 557 more rows</code></pre>
<p>These steps have taken us from a table of 34,786 observations to a table of 567 observations.</p>
</div>
<div id="create-a-plot-with-ggplot" class="section level3">
<h3><span class="header-section-number">2.4.4</span> Create a plot with <code>ggplot</code></h3>
<p>Now we can create a line and point plot, using the <code>by_quarter</code> data as our first <code>ggplot()</code>
argument.</p>
<p>For the aesthetics we are plotting the time on the
x-axis using the <code>quarter</code> variable, and the quarterly <code>mean_captures</code> on the
y-axis, and we colour the data by <code>rodent_type</code>.</p>
<p>Then we create line and point geometric mappings, and split the plot into two
facets using <code>facet_wrap</code> according to <code>plot_type</code>.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1"><span class="kw">ggplot</span>(by_quarter,</a>
<a class="sourceLine" id="cb57-2" title="2">       <span class="kw">aes</span>(<span class="dt">x=</span>quarter,<span class="dt">y=</span>mean_captures,<span class="dt">colour=</span>rodent_type)) <span class="op">+</span></a>
<a class="sourceLine" id="cb57-3" title="3"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb57-4" title="4"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb57-5" title="5"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>plot_type)</a></code></pre></div>
<pre><code>## Warning: Removed 2 rows containing missing values (geom_path).</code></pre>
<pre><code>## Warning: Removed 5 rows containing missing values (geom_point).</code></pre>
<p><img src="coding-together_files/figure-html/plot-quarter-all-1.png" width="100%" /></p>
<p>But it would be more useful to only plot the Kangaroo Rats and Granivores
data, so let’s filter out the other species. And move the legend to the bottom
of the plot and add a title.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1">by_quarter <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb60-2" title="2"><span class="st">        </span><span class="kw">filter</span>(rodent_type <span class="op">!=</span><span class="st"> &quot;Other&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb60-3" title="3"><span class="st">        </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>quarter,<span class="dt">y=</span>mean_captures,<span class="dt">colour=</span>rodent_type)) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-4" title="4"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb60-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb60-6" title="6"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>plot_type) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-7" title="7"><span class="st">        </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;bottom&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-8" title="8"><span class="st">        </span><span class="kw">ggtitle</span>(<span class="st">&quot;How does excluding Kangaroo Rats </span></a>
<a class="sourceLine" id="cb60-9" title="9"><span class="st">                effect Granivore populations?&quot;</span>, </a>
<a class="sourceLine" id="cb60-10" title="10">                <span class="dt">subtitle =</span> <span class="st">&quot;Mean quarterly observations&quot;</span>)</a></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_path).</code></pre>
<pre><code>## Warning: Removed 3 rows containing missing values (geom_point).</code></pre>
<p><img src="coding-together_files/figure-html/plot-quarter-1.png" width="100%" /></p>
<blockquote>
<p><strong>Challenge</strong> Can you do a similar analysis, but plotting the data only from 1980 to 2000 and by semester?</p>
</blockquote>
<!--chapter:end:02-data-wrangling.Rmd-->
</div>
</div>
</div>
<div id="data-wrangle-2" class="section level1">
<h1><span class="header-section-number">3</span> Data wrangling II</h1>
<p>Following on from chapter 2 this lesson deals with some
common tidying problems with data using the <a href="https://tidyr.tidyverse.org/"><code>tidyr</code> package</a> . By the end of this chapter the learner
will:</p>
<ul>
<li>have learnt how to transform rows and columns to reorganise data</li>
<li>have learnt how to join data contained in separate tables into a single table</li>
<li>have learnt some ways to deal with missing values</li>
</ul>
<div id="reshaping-data-with-pivots" class="section level2">
<h2><span class="header-section-number">3.1</span> Reshaping data with pivots</h2>
<p>As you will recall <a href="tidy-data">tidy data</a> means that in a table:</p>
<ol style="list-style-type: decimal">
<li>Every variable has its own column.</li>
<li>Every observation has its own row.</li>
<li>Each value has its own cell.</li>
</ol>
<p>Two common problems making your data untidy are that:</p>
<ol style="list-style-type: decimal">
<li>A single variable is spread across multiple colummns.</li>
<li>A single observation is distributed across multiple rows.</li>
</ol>
<p>In the first case the column names are actually the variable we are
interested in, making our table <strong>wide</strong>.</p>
<p>In the second case, the observation is contained in several rows instead
of a single row, making our table <strong>long</strong>.</p>
<p>Hence <code>tidyr</code> has functions that <strong>pivot</strong> (as in turning) a table from <strong>wide-to-long</strong> by reducing the number of columns and increasing the number of rows. Or from <strong>long-to-wide</strong> by reducing the number of rows and increasing the number of columns.</p>
<p>Usually, the hard part is identifying in a dataset our variables and our
observations, as it is not always obvious which is which.</p>
<div id="tidyrpivot_longer" class="section level3">
<h3><span class="header-section-number">3.1.1</span> <code>tidyr::pivot_longer</code></h3>
<p>First we’ll consider the case when our variable has been recorded as
column names by returning to a version of the <a href="portal-project">Portal surveys data</a>.</p>
<p>A table containing the mean weight of 10 rodent species on each plot from the rodent survey data
can be read directly into a <code>surveys_spread</code> object using the code below.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1">surveys_spread &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/ab604/ab604.github.io/master/docs/surveys_spread.csv&quot;</span>)</a></code></pre></div>
<p>Feel free to explore the data, and snapshot is shown in Figure @ref(fig:pivot-long).</p>
<p>Imagine that we recorded the mean weight of each rodent species on a plot in the field.
It makes sense to put the species as column headings, along with the plot id and
then record the values in each cell.</p>
<p>However, really our variables of interest are the rodent species and our observational
units, the rows, should contain the mean weight for a rodent species in a plot. Hence we
need to reduce the number of columns and create a longer table.</p>
<p>To do this we <code>pivot_longer()</code> by using <code>names_to = "genus"</code> to create a new <code>genus</code>
variable for the exisiting column heading, and <code>values_to = "mean_weight"</code> to create
a variable <code>mean_weight</code> for the values. We put a minus sign before the
variable <code>-plot_id</code> to tell the function not to use these values in the new variable column.</p>
<p>(ref:pivl) <code>tidyr::pivot_longer</code></p>
<div class="figure" style="text-align: center">
<img src="img/pivot_longer_R.png" alt="(ref:pivl)" width="100%" />
<p class="caption">
(#fig:pivot-long)(ref:pivl)
</p>
</div>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1">surveys_spread <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb64-2" title="2"><span class="st">        </span><span class="kw">pivot_longer</span>(<span class="dt">names_to =</span> <span class="st">&quot;genus&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;mean_weight&quot;</span>, <span class="op">-</span>plot_id) </a></code></pre></div>
<pre><code>## # A tibble: 240 x 3
##    plot_id genus           mean_weight
##      &lt;dbl&gt; &lt;chr&gt;                 &lt;dbl&gt;
##  1       1 Baiomys                7   
##  2       1 Chaetodipus           22.2 
##  3       1 Dipodomys             60.2 
##  4       1 Neotoma              156.  
##  5       1 Onychomys             27.7 
##  6       1 Perognathus            9.62
##  7       1 Peromyscus            22.2 
##  8       1 Reithrodontomys       11.4 
##  9       1 Sigmodon              NA   
## 10       1 Spermophilus          NA   
## # ... with 230 more rows</code></pre>
</div>
<div id="tidyrpivot_wider" class="section level3">
<h3><span class="header-section-number">3.1.2</span> <code>tidyr::pivot_wider</code></h3>
<p>(ref:pivw) <code>tidyr::pivot_wider</code></p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1">surveys_gw &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/ab604/ab604.github.io/master/docs/surveys_grouped_weight.csv&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="img/pivot_wider_R.png" alt="(ref:pivw)" width="100%" />
<p class="caption">
(#fig:pivot-wider)(ref:pivw)
</p>
</div>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" title="1">surveys_gw <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb67-2" title="2"><span class="st">        </span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> genus, <span class="dt">values_from =</span> mean_weight) </a></code></pre></div>
<pre><code>## # A tibble: 24 x 11
##    plot_id Baiomys Chaetodipus Dipodomys Neotoma Onychomys Perognathus
##      &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
##  1       1    7           22.2      60.2    156.      27.7        9.62
##  2       2    6           25.1      55.7    169.      26.9        6.95
##  3       3    8.61        24.6      52.0    158.      26.0        7.51
##  4       5    7.75        18.0      51.1    190.      27.0        8.66
##  5      18    9.5         26.8      61.4    149.      26.6        8.62
##  6      19    9.53        26.4      43.3    120       23.8        8.09
##  7      20    6           25.1      65.9    155.      25.2        8.14
##  8      21    6.67        28.2      42.7    138.      24.6        9.19
##  9       4   NA           23.0      57.5    164.      28.1        7.82
## 10       6   NA           24.9      58.6    180.      25.9        7.81
## # ... with 14 more rows, and 4 more variables: Peromyscus &lt;dbl&gt;,
## #   Reithrodontomys &lt;dbl&gt;, Sigmodon &lt;dbl&gt;, Spermophilus &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1">knitr<span class="op">::</span><span class="kw">knit_exit</span>()</a></code></pre></div>
<div id="refs" class="references">
<div id="ref-ihaka1996">
<p>Ihaka, Ross, and Robert Gentleman. 1996. “R: A Language for Data Analysis and Graphics.” <em>Journal of Computational and Graphical Statistics</em> 5 (3): 299–314.</p>
</div>
<div id="ref-R-base">
<p>R Core Team. 2019. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.</p>
</div>
<div id="ref-rstudioteam2018">
<p>RStudio Team. 2018. <em>RStudio: Integrated Development Environment for R</em>. Boston, MA: RStudio, Inc. <a href="http://www.rstudio.com/">http://www.rstudio.com/</a>.</p>
</div>
<div id="ref-R-tidyverse">
<p>Wickham, Hadley. 2017. <em>Tidyverse: Easily Install and Load the ’Tidyverse’</em>. <a href="https://CRAN.R-project.org/package=tidyverse">https://CRAN.R-project.org/package=tidyverse</a>.</p>
</div>
<div id="ref-Wilson2018">
<p>Wilson, Greg, ed. 2018. <em>Teaching Tech Together. 2018,, Http://Teachtogether.tech/.</em> Lulu.com. <a href="http://teachtogether.tech/">http://teachtogether.tech/</a>.</p>
</div>
<div id="ref-R-bookdown">
<p>Xie, Yihui. 2019. <em>Bookdown: Authoring Books and Technical Documents with R Markdown</em>. <a href="https://CRAN.R-project.org/package=bookdown">https://CRAN.R-project.org/package=bookdown</a>.</p>
</div>
</div>
</div>
</div>
</div>
<!--bookdown:body:end-->
            </section>

          </div>
        </div>
      </div>
<!--bookdown:link_prev-->
<!--bookdown:link_next-->
    </div>
  </div>
<!--bookdown:config-->

</body>

</html>
