<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Data wrangling I | Coding togetheR</title>
  <meta name="description" content="Materials for the Coding TogetheR workshops" />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Data wrangling I | Coding togetheR" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://ab604.github.io/docs/coding-together-2019/" />
  <meta property="og:image" content="https://ab604.github.io/docs/coding-together-2019/img/Carrick-bend-Guten-Verrill-modified.png" />
  <meta property="og:description" content="Materials for the Coding TogetheR workshops" />
  <meta name="github-repo" content="ab604/coding-together" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Data wrangling I | Coding togetheR" />
  <meta name="twitter:site" content="@alistair604" />
  <meta name="twitter:description" content="Materials for the Coding TogetheR workshops" />
  <meta name="twitter:image" content="https://ab604.github.io/docs/coding-together-2019/img/Carrick-bend-Guten-Verrill-modified.png" />

<meta name="author" content="Alistair Bailey" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="getting-started.html"/>
<link rel="next" href="data-wrangle-2.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Coding togetheR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-and-rstudio"><i class="fa fa-check"></i>R and RStudio</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#who-is-coding-together-for"><i class="fa fa-check"></i>Who is coding togetheR for?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#code-of-conduct"><i class="fa fa-check"></i>Code of conduct</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting started in R and RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#coding-is-for-everyone"><i class="fa fa-check"></i><b>1.1</b> Coding is for everyone</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#a-little-background-and-philosophy"><i class="fa fa-check"></i><b>1.2</b> A little background and philosophy</a><ul>
<li class="chapter" data-level="1.2.1" data-path="getting-started.html"><a href="getting-started.html#what-is-r"><i class="fa fa-check"></i><b>1.2.1</b> What is R?</a></li>
<li class="chapter" data-level="1.2.2" data-path="getting-started.html"><a href="getting-started.html#why-learn-to-code-at-all"><i class="fa fa-check"></i><b>1.2.2</b> Why learn to code at all?</a></li>
<li class="chapter" data-level="1.2.3" data-path="getting-started.html"><a href="getting-started.html#a-little-goes-a-long-way"><i class="fa fa-check"></i><b>1.2.3</b> A little goes a long way</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#rstudio"><i class="fa fa-check"></i><b>1.3</b> RStudio</a><ul>
<li class="chapter" data-level="1.3.1" data-path="getting-started.html"><a href="getting-started.html#what-is-real"><i class="fa fa-check"></i><b>1.3.1</b> What is real?</a></li>
<li class="chapter" data-level="1.3.2" data-path="getting-started.html"><a href="getting-started.html#where-am-i"><i class="fa fa-check"></i><b>1.3.2</b> Where am I?</a></li>
<li class="chapter" data-level="1.3.3" data-path="getting-started.html"><a href="getting-started.html#getting-help"><i class="fa fa-check"></i><b>1.3.3</b> Getting help</a></li>
<li class="chapter" data-level="1.3.4" data-path="getting-started.html"><a href="getting-started.html#install-packages"><i class="fa fa-check"></i><b>1.3.4</b> Installing and loading packages</a></li>
<li class="chapter" data-level="1.3.5" data-path="getting-started.html"><a href="getting-started.html#functions-1"><i class="fa fa-check"></i><b>1.3.5</b> Using functions</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#workflow"><i class="fa fa-check"></i><b>1.4</b> A project orientated workflow</a><ul>
<li class="chapter" data-level="1.4.1" data-path="getting-started.html"><a href="getting-started.html#rstudio-projects"><i class="fa fa-check"></i><b>1.4.1</b> RStudio Projects</a></li>
<li class="chapter" data-level="1.4.2" data-path="getting-started.html"><a href="getting-started.html#r-notebooks-and-r-scripts"><i class="fa fa-check"></i><b>1.4.2</b> R notebooks and R scripts</a></li>
<li class="chapter" data-level="1.4.3" data-path="getting-started.html"><a href="getting-started.html#here"><i class="fa fa-check"></i><b>1.4.3</b> Level up with the <code>here</code> package</a></li>
<li class="chapter" data-level="1.4.4" data-path="getting-started.html"><a href="getting-started.html#names"><i class="fa fa-check"></i><b>1.4.4</b> Naming things</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="getting-started.html"><a href="getting-started.html#the-tidyverse-and-tidy-data"><i class="fa fa-check"></i><b>1.5</b> The tidyverse and tidy data</a></li>
<li class="chapter" data-level="1.6" data-path="getting-started.html"><a href="getting-started.html#r-atoms"><i class="fa fa-check"></i><b>1.6</b> Atoms of R</a></li>
<li class="chapter" data-level="1.7" data-path="getting-started.html"><a href="getting-started.html#assignment"><i class="fa fa-check"></i><b>1.7</b> Assigning objects</a><ul>
<li class="chapter" data-level="1.7.1" data-path="getting-started.html"><a href="getting-started.html#indexing-and-subsetting"><i class="fa fa-check"></i><b>1.7.1</b> Indexing and subsetting</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="getting-started.html"><a href="getting-started.html#lists-matrices-and-arrays"><i class="fa fa-check"></i><b>1.8</b> Lists, matrices and arrays</a><ul>
<li class="chapter" data-level="1.8.1" data-path="getting-started.html"><a href="getting-started.html#matrices-and-arrays"><i class="fa fa-check"></i><b>1.8.1</b> Matrices and arrays</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="getting-started.html"><a href="getting-started.html#factors"><i class="fa fa-check"></i><b>1.9</b> Factors</a></li>
<li class="chapter" data-level="1.10" data-path="getting-started.html"><a href="getting-started.html#data-frames"><i class="fa fa-check"></i><b>1.10</b> Data frames</a><ul>
<li class="chapter" data-level="1.10.1" data-path="getting-started.html"><a href="getting-started.html#attributes"><i class="fa fa-check"></i><b>1.10.1</b> Attributes</a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="getting-started.html"><a href="getting-started.html#plotting-data"><i class="fa fa-check"></i><b>1.11</b> Plotting data</a></li>
<li class="chapter" data-level="1.12" data-path="getting-started.html"><a href="getting-started.html#exporting-data"><i class="fa fa-check"></i><b>1.12</b> Exporting data</a><ul>
<li class="chapter" data-level="1.12.1" data-path="getting-started.html"><a href="getting-started.html#readr"><i class="fa fa-check"></i><b>1.12.1</b> readr</a></li>
<li class="chapter" data-level="1.12.2" data-path="getting-started.html"><a href="getting-started.html#ggsave"><i class="fa fa-check"></i><b>1.12.2</b> ggsave</a></li>
<li class="chapter" data-level="1.12.3" data-path="getting-started.html"><a href="getting-started.html#exercise"><i class="fa fa-check"></i><b>1.12.3</b> Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html"><i class="fa fa-check"></i><b>2</b> Data wrangling I</a><ul>
<li class="chapter" data-level="2.1" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#data-organisation-in-spreadsheets"><i class="fa fa-check"></i><b>2.1</b> Data organisation in spreadsheets</a><ul>
<li class="chapter" data-level="2.1.1" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#flat-formats-and-excel-files"><i class="fa fa-check"></i><b>2.1.1</b> Flat formats and Excel files</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#portal-project"><i class="fa fa-check"></i><b>2.2</b> The Portal Project data</a><ul>
<li class="chapter" data-level="2.2.1" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#downloading-and-importing-the-data"><i class="fa fa-check"></i><b>2.2.1</b> Downloading and importing the data</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#dplyr"><i class="fa fa-check"></i><b>2.3</b> <code>dplyr</code></a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#filter-rows-with-filter"><i class="fa fa-check"></i><b>2.3.1</b> Filter rows with <code>filter()</code></a></li>
<li class="chapter" data-level="2.3.2" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#arrange-rows-with-arrange"><i class="fa fa-check"></i><b>2.3.2</b> Arrange rows with <code>arrange()</code></a></li>
<li class="chapter" data-level="2.3.3" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#select-columns-with-select"><i class="fa fa-check"></i><b>2.3.3</b> Select columns with <code>select()</code></a></li>
<li class="chapter" data-level="2.3.4" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#create-new-variables-with-mutate"><i class="fa fa-check"></i><b>2.3.4</b> Create new variables with <code>mutate()</code></a></li>
<li class="chapter" data-level="2.3.5" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#grouped-summaries-with-group_by-and-summarise"><i class="fa fa-check"></i><b>2.3.5</b> Grouped summaries with <code>group_by()</code> and <code>summarise()</code></a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#using-dpylr-to-explore-the-effect-of-kangaroo-rat-exclusion-on-granivore-populations"><i class="fa fa-check"></i><b>2.4</b> Using <code>dpylr</code> to explore the effect of Kangaroo Rat exclusion on Granivore populations</a><ul>
<li class="chapter" data-level="2.4.1" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#re-cap-of-filter-and-mutate"><i class="fa fa-check"></i><b>2.4.1</b> Re-cap of <code>filter()</code> and <code>mutate()</code></a></li>
<li class="chapter" data-level="2.4.2" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#use-lubridate-to-create-new-time-variables"><i class="fa fa-check"></i><b>2.4.2</b> Use <code>lubridate</code> to create new time variables</a></li>
<li class="chapter" data-level="2.4.3" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#group-and-summarise-the-data-into-quarterly-observations"><i class="fa fa-check"></i><b>2.4.3</b> Group and summarise the data into quarterly observations</a></li>
<li class="chapter" data-level="2.4.4" data-path="data-wrangle-1.html"><a href="data-wrangle-1.html#create-a-plot-with-ggplot"><i class="fa fa-check"></i><b>2.4.4</b> Create a plot with <code>ggplot</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-wrangle-2.html"><a href="data-wrangle-2.html"><i class="fa fa-check"></i><b>3</b> Data wrangling II</a></li>
<li class="chapter" data-level="4" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>4</b> Functions</a></li>
<li class="chapter" data-level="5" data-path="eda.html"><a href="eda.html"><i class="fa fa-check"></i><b>5</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="6" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>6</b> Visualistion</a></li>
<li class="chapter" data-level="7" data-path="reports.html"><a href="reports.html"><i class="fa fa-check"></i><b>7</b> Reports</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Coding togetheR</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-wrangle-1" class="section level1">
<h1><span class="header-section-number">2</span> Data wrangling I</h1>
<p>By the end of this chapter you will:</p>
<ul>
<li>have learnt to load csv files</li>
<li>have used the key verbs of the <code>dplyr</code> package for transforming data to
arrange and filter observations, select variables, create new variables, and
create summaries.</li>
<li>have learnt how to combine functions with the pipe <code>%&gt;%</code> from the <code>magrittr</code> package
to combine tasks</li>
</ul>
<p>The following sections are based upon the <a href="https://r4ds.had.co.nz/transform.html">data transformation chapter</a> in R4DS and the
<a href="https://datacarpentry.org/R-ecology-lesson/index.html">Data Carpentry ecology lesson</a>.</p>
<div id="data-organisation-in-spreadsheets" class="section level2">
<h2><span class="header-section-number">2.1</span> Data organisation in spreadsheets</h2>
<p>Karl Broman and Kara Woo wrote as
paper all about <a href="https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989">Data Organization in Spreadsheets</a>.</p>
<p>It’s full of practical advice and context and well worth reading for helping
you think about best practices for organising your data for yourself, and when working with others.</p>
<div id="flat-formats-and-excel-files" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Flat formats and Excel files</h3>
<p>File formats like <code>.csv</code> and <code>.tsv</code>, comma separated variables and tab separated variables
respectively are plain text files. That is to
say they contain only the data, as text information, and are the simplest and most
convenient way to share data as most software can read and
interpret them.</p>
<p>Excel files saves files into its own proprietary format <code>.xls</code> or <code>.xlsx</code> that holds
information in addition to the data itself. For reading and
writing excel files in R, the tidyverse <code>readxl</code> package is very useful.</p>
</div>
</div>
<div id="portal-project" class="section level2">
<h2><span class="header-section-number">2.2</span> The Portal Project data</h2>
<p>In this chapter we are going to focus on data from the <a href="https://portal.weecology.org/">Portal Project</a>,
which is a long running survey of rodents and other species in the Chihuahuan Desert,
as analysed in the 1994 paper by Heske et. al:</p>
<p><strong>Long-Term Experimental Study of a Chihuahuan Desert Rodent Community: 13 Years
of Competition</strong>, DOI: 10.2307/1939547.</p>
<p>Specifically they explored the effect on the populations of small
seed eating rodents as a result of the exclusion of larger competitor kangaroo
rats over a period from 1977 to 1991.</p>
<p>We’ll also use some of their data to explore this question: <strong>What is the effect
of the exclusion of kangaroo rats from a plot of land on the granivore population?</strong></p>
<p>Figure <a href="data-wrangle-1.html#fig:k-rat">2.1</a> shows an image of one of the species of kangaroo rats excluded during the
study.</p>

<div class="figure" style="text-align: center"><span id="fig:k-rat"></span>
<img src="img/kratsep12.jpg" alt="Merriam’s kangaroo rat, Dipodomys merriami" width="100%" />
<p class="caption">
Figure 2.1: <a href="https://portalproject.wordpress.com/">Merriam’s kangaroo rat, Dipodomys merriami</a>
</p>
</div>
<p>Figure <a href="data-wrangle-1.html#fig:fence">2.2</a> indicates how the exclusion works, where a for number of
fenced plots the kangaroo rats were either able to enter by a hole or kept out.</p>

<div class="figure" style="text-align: center"><span id="fig:fence"></span>
<img src="img/fence_hole.JPG" alt="Kangaroo Rat exclusion" width="60%" />
<p class="caption">
Figure 2.2: Kangaroo Rat exclusion
</p>
</div>
<p>The plots are 50 metres by 50 metres, and a survey of the species within each
plot has been ongoing once a month for many years.</p>
<p>The dataset is stored as a comma separated value (CSV) file.
Each row holds information for a single animal, and the columns represent:</p>
<table>
<thead>
<tr class="header">
<th>Column</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>record_id</td>
<td>Unique id for the observation</td>
<td>numeric</td>
</tr>
<tr class="even">
<td>month</td>
<td>month of observation</td>
<td>numeric</td>
</tr>
<tr class="odd">
<td>day</td>
<td>day of observation</td>
<td>numeric</td>
</tr>
<tr class="even">
<td>year</td>
<td>year of observation</td>
<td>numeric</td>
</tr>
<tr class="odd">
<td>plot_id</td>
<td>ID of a particular plot</td>
<td>numeric</td>
</tr>
<tr class="even">
<td>species_id</td>
<td>2-letter code</td>
<td>character</td>
</tr>
<tr class="odd">
<td>sex</td>
<td>sex of animal (“M”, “F”)</td>
<td>character</td>
</tr>
<tr class="even">
<td>hindfoot_length</td>
<td>length of the hindfoot in mm</td>
<td>numeric</td>
</tr>
<tr class="odd">
<td>weight</td>
<td>weight of the animal in grams</td>
<td>numeric</td>
</tr>
<tr class="even">
<td>genus</td>
<td>genus of animal</td>
<td>character</td>
</tr>
<tr class="odd">
<td>species</td>
<td>species of animal</td>
<td>character</td>
</tr>
<tr class="even">
<td>taxa</td>
<td>e.g. Rodent, Reptile, Bird, Rabbit</td>
<td>character</td>
</tr>
<tr class="odd">
<td>plot_type</td>
<td>type of plot</td>
<td>character</td>
</tr>
</tbody>
</table>
<p>The rodents species surveyed are:</p>
<p><strong>Kangaroo Rats</strong></p>
<table>
<thead>
<tr class="header">
<th>species_id</th>
<th>Scientific name</th>
<th>Common name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DM</td>
<td>Dipodomys merriami</td>
<td>Merriam’s kangaroo rat</td>
</tr>
<tr class="even">
<td>DO</td>
<td>Dipodomys ordii</td>
<td>Ord’s kangaroo rat</td>
</tr>
<tr class="odd">
<td>DS</td>
<td>Dipodomys spectabilis</td>
<td>Banner-tailed kangaroo rat</td>
</tr>
</tbody>
</table>
<p><strong>Granivores</strong></p>
<table>
<thead>
<tr class="header">
<th>species_id</th>
<th>Scientific name</th>
<th>Common name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PP</td>
<td>Chaetodipus penicillatus</td>
<td>Desert pocket mouse</td>
</tr>
<tr class="even">
<td>PF</td>
<td>Perognathus flavus</td>
<td>Silky pocket mouse</td>
</tr>
<tr class="odd">
<td>PE</td>
<td>Peromyscus eremicus</td>
<td>Cactus mouse</td>
</tr>
<tr class="even">
<td>PM</td>
<td>Peromyscus maniculatus</td>
<td>Deer Mouse</td>
</tr>
<tr class="odd">
<td>RM</td>
<td>Reithrodontomys megalotis</td>
<td>Western harvest mouse</td>
</tr>
</tbody>
</table>
<div id="downloading-and-importing-the-data" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Downloading and importing the data</h3>
<p><strong>First create a <a href="getting-started.html#workflow">R project</a> for this analysis e.g <code>coding-together-week-2</code></strong></p>
<p>The dataset is stored on-line, so we use the utility function
<code>download.file()</code> to download the csv file to our data folder.
(Did you create a data folder in the project directory?)</p>
<p>Here we pass the <code>url =</code> and <code>destfile =</code> arguments to <code>download.file()</code>.</p>
<p>As we have the <code>tidyverse</code> packages we can use the <code>readr</code> package it contains,
which has many functions for reading files, including <code>read_csv()</code>.
The advantage of <code>read_csv()</code> over base R <code>read.csv()</code> is that it defaults to reading strings as
character vectors rather than factors (categorical variables) which
is usually what we want.</p>
<p>As we read the data into our environment we need to assign a label
to the object we are creating. Here we assign the dataset to an object
called <code>surveys</code> using the <code>&lt;-</code> assignment operator.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="co"># Download the data</span></a>
<a class="sourceLine" id="cb31-2" title="2"><span class="kw">download.file</span>(<span class="dt">url=</span><span class="st">&quot;https://ndownloader.figshare.com/files/2292169&quot;</span>,</a>
<a class="sourceLine" id="cb31-3" title="3">              <span class="dt">destfile =</span> <span class="st">&quot;data/portal_data_joined.csv&quot;</span>)</a>
<a class="sourceLine" id="cb31-4" title="4"></a>
<a class="sourceLine" id="cb31-5" title="5"><span class="co"># Read into R as an object called surveys</span></a>
<a class="sourceLine" id="cb31-6" title="6">surveys &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/portal_data_joined.csv&quot;</span>)</a></code></pre></div>
</div>
</div>
<div id="dplyr" class="section level2">
<h2><span class="header-section-number">2.3</span> <code>dplyr</code></h2>
<p><a href="https://dplyr.tidyverse.org/"><code>dplyr</code></a> <em>“is a grammar of data manipulation”</em>.
Concretely, it’s a package of functions from the tidyverse that have been
created for tasks that require manipulation of data stored in <a href="data-frames">data frames</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:dplyr-name"></span>
<img src="img/dplyr-name-github.png" alt="[Why is it called `dplyr`?](https://github.com/tidyverse/dplyr/issues/1857)" width="100%" />
<p class="caption">
Figure 2.3: <a href="https://github.com/tidyverse/dplyr/issues/1857">Why is it called <code>dplyr</code>?</a>
</p>
</div>
<p>We’re going to use the most common verbs in <code>dplyr</code> to examine the Portal Project
surveys data.</p>
<div id="filter-rows-with-filter" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Filter rows with <code>filter()</code></h3>
<p>The first verb to consider is the <code>filter()</code> function which enables us to subset observations
based on their value.</p>
<p>Consider the surveys data and sub-setting observations that only occurred from
1985 onwards. It’s fairly natural to say <em>“filter the survey where the year
variable is equal or greater than 1985”</em>. And indeed this is how we use <code>filter()</code>
as a verb.</p>
<p>Figure <a href="data-wrangle-1.html#fig:dplyr-filter">2.4</a> shows how
we give the filter function two arguments. The first is the
data frame, the second is the variable and condition on which we wish to filter.</p>
<p>An alternative way to use <code>filter()</code> is to “pipe” the function using pipe <code>%&gt;%</code> from the <code>magrittr</code> package
which you can think of as using the word <em>“then”</em>. We take our data set <em>then</em> filter it.
Using the pipe makes more sense when combining several operations.</p>
<blockquote>
<p>Ctl+Shift+M is a keyboard short cut to create a pipe.</p>
</blockquote>
<p>For the filter itself, from R4DS:</p>
<p><em>“To use filtering effectively, you have to know how to select the observations t
hat you want using the comparison operators. R provides the standard suite: <code>&gt;</code>,
<code>&gt;=</code>, <code>&lt;</code>, <code>&lt;=</code>, <code>!=</code> (not equal), and <code>==</code> (equal)….For other types of combinations,
you’ll need to use Boolean operators yourself: <code>&amp;</code> is “and”, <code>|</code> is “or”, and <code>!</code> is “not”."</em></p>
<p>See <a href="https://r4ds.had.co.nz/transform.html#fig:bool-ops">Figure 5.1</a> in R4DS for
to see how these operators work.</p>
<p>(Note that we aren’t assigning the output to an object here, so we can see it.)</p>

<div class="figure" style="text-align: center"><span id="fig:dplyr-filter"></span>
<img src="img/dplyr_filter.png" alt="dplyr::filter()" width="100%" />
<p class="caption">
Figure 2.4: <code>dplyr::filter()</code>
</p>
</div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1"><span class="co"># Filter observations that only occurred from 1985 onwards</span></a>
<a class="sourceLine" id="cb32-2" title="2"> <span class="kw">filter</span>(surveys, year <span class="op">&gt;=</span><span class="st"> </span><span class="dv">1985</span>)</a></code></pre></div>
<pre><code>## # A tibble: 25,290 x 13
##    record_id month   day  year plot_id species_id sex   hindfoot_length
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;
##  1     10606     7    24  1985       2 NL         F                  30
##  2     10617     7    24  1985       2 NL         M                  32
##  3     10627     7    24  1985       2 NL         F                  32
##  4     10720     8    20  1985       2 NL         F                  31
##  5     10923    10    13  1985       2 NL         F                  31
##  6     10949    10    13  1985       2 NL         F                  33
##  7     11215    12     8  1985       2 NL         F                  32
##  8     11329     3     9  1986       2 NL         M                  34
##  9     11496     5    11  1986       2 NL         F                  31
## 10     11498     5    11  1986       2 NL         F                  31
## # ... with 25,280 more rows, and 5 more variables: weight &lt;dbl&gt;,
## #   genus &lt;chr&gt;, species &lt;chr&gt;, taxa &lt;chr&gt;, plot_type &lt;chr&gt;</code></pre>
<p>An example using Boolean logic, would be to use the “or” operator <code>|</code> to filter
for the observations only occurring on <code>plot_type</code>’s control or long term kangaroo
rat exclusion. This time we assign the output to a new data frame called <code>surveys_filtered</code>.</p>
<p><strong>Note:</strong> as <code>plot_type</code> is a character vector we put the terms in quotes,
and also the double equals sign <code>==</code> “for equal to”.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1"><span class="co"># Keep only the rows corresponding with the Control and Long-term Krat Exclosure</span></a>
<a class="sourceLine" id="cb34-2" title="2">surveys_filtered &lt;-<span class="st"> </span>surveys <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb34-3" title="3"><span class="st">        </span><span class="kw">filter</span>(plot_type <span class="op">==</span><span class="st"> &quot;Control&quot;</span> <span class="op">|</span><span class="st"> </span>plot_type <span class="op">==</span><span class="st"> &quot;Long-term Krat Exclosure&quot;</span>)</a></code></pre></div>
<p><strong>Note:</strong> <code>filter()</code> only includes rows where the condition is TRUE; it excludes both <code>FALSE</code> and missing <code>NA</code> values.
We have to explicitly ask to keep <code>NA</code> values using <code>is.na()</code> as an additional filter.</p>
<blockquote>
<p>How did I know which <code>plot_type</code>’s to filter?
I used the <code>dplyr::distinct()</code> function, passing the <code>surveys</code> data frame
and the <code>plot_type</code> variable to obtain a list of the unique plot types,
from which I determined the <code>Control</code> and <code>Long-term Krat Exclosure</code> plots
were the ones I was after. Note that you need to add the argument
<code>.keep_all = TRUE</code> to <code>distinct()</code> to return all the columns in the
data frame</p>
</blockquote>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1"><span class="kw">distinct</span>(surveys, plot_type)</a></code></pre></div>
<pre><code>## # A tibble: 5 x 1
##   plot_type                
##   &lt;chr&gt;                    
## 1 Control                  
## 2 Long-term Krat Exclosure 
## 3 Short-term Krat Exclosure
## 4 Rodent Exclosure         
## 5 Spectab exclosure</code></pre>
</div>
<div id="arrange-rows-with-arrange" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Arrange rows with <code>arrange()</code></h3>
<p>The next verb is <code>arrange()</code> which also operates on the rows, and enables
you to arrange the observations in a data frame according to one or more variables.</p>
<p>As with <code>filter()</code> we supply the variable or variables of interest as the arguments
to <code>arrange()</code>.</p>
<p>From <a href="https://r4ds.had.co.nz/transform.html#arrange-rows-with-arrange">R4DS</a>:</p>
<p><em>“If you provide more than one column name, each additional column will be used to
break ties in the values of preceding columns…
Missing values are always sorted at the end.”</em></p>
<p>Figure <a href="data-wrangle-1.html#fig:dplyr-arrange">2.5</a> shows how to arrange the observations according to the <code>record_id</code>
variable.</p>

<div class="figure" style="text-align: center"><span id="fig:dplyr-arrange"></span>
<img src="img/dplyr_arrange.png" alt="dplyr::arrange()" width="100%" />
<p class="caption">
Figure 2.5: <code>dplyr::arrange()</code>
</p>
</div>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1">surveys <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(record_id)</a></code></pre></div>
<pre><code>## # A tibble: 34,786 x 13
##    record_id month   day  year plot_id species_id sex   hindfoot_length
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;
##  1         1     7    16  1977       2 NL         M                  32
##  2         2     7    16  1977       3 NL         M                  33
##  3         3     7    16  1977       2 DM         F                  37
##  4         4     7    16  1977       7 DM         M                  36
##  5         5     7    16  1977       3 DM         M                  35
##  6         6     7    16  1977       1 PF         M                  14
##  7         7     7    16  1977       2 PE         F                  NA
##  8         8     7    16  1977       1 DM         M                  37
##  9         9     7    16  1977       1 DM         F                  34
## 10        10     7    16  1977       6 PF         F                  20
## # ... with 34,776 more rows, and 5 more variables: weight &lt;dbl&gt;,
## #   genus &lt;chr&gt;, species &lt;chr&gt;, taxa &lt;chr&gt;, plot_type &lt;chr&gt;</code></pre>
<p>Or we could use <code>arrange()</code> to find the record with the shortest hindfoot.
<em>Note:</em> <code>arrange()</code> defaults to ascending order.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1">surveys <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(hindfoot_length)</a></code></pre></div>
<pre><code>## # A tibble: 34,786 x 13
##    record_id month   day  year plot_id species_id sex   hindfoot_length
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;
##  1     31400     9    30  2000      19 PB         M                   2
##  2     10067     3    16  1985      19 RM         M                   6
##  3     19567     1     8  1992      19 BA         M                   6
##  4     19015     9     9  1991      19 BA         F                   7
##  5     21036     8    19  1993      21 PF         F                   7
##  6     31457     9    31  2000       6 RM         M                   8
##  7     19191    10    11  1991      13 PF         F                   8
##  8      5801     4    29  1982       7 RM         &lt;NA&gt;                8
##  9     33647     3    14  2002       3 PF         M                   9
## 10     20562    12    22  1992       5 RM         F                   9
## # ... with 34,776 more rows, and 5 more variables: weight &lt;dbl&gt;,
## #   genus &lt;chr&gt;, species &lt;chr&gt;, taxa &lt;chr&gt;, plot_type &lt;chr&gt;</code></pre>
<p>To find the Cactus Mouse, (<code>species_id == "PE"</code>) with the longest hindfoot we combine
<code>filter()</code> with <code>arrangee()</code> using the pipe:</p>
<p><em>Hint</em> Use the <code>desc()</code> function to arrange from biggest to smallest.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1">surveys <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb41-2" title="2"><span class="st">        </span><span class="kw">filter</span>(species_id <span class="op">==</span><span class="st"> &quot;PE&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb41-3" title="3"><span class="st">        </span><span class="kw">arrange</span>(<span class="kw">desc</span>(hindfoot_length))</a></code></pre></div>
<pre><code>## # A tibble: 1,299 x 13
##    record_id month   day  year plot_id species_id sex   hindfoot_length
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;
##  1      1202     9     3  1978       7 PE         F                  30
##  2       517     1     8  1978       2 PE         M                  26
##  3     32443     8    25  2001      23 PE         F                  24
##  4      5080    12    30  1981      15 PE         F                  23
##  5      5090    12    30  1981      15 PE         F                  23
##  6     33700     3    14  2002       9 PE         F                  23
##  7       604     2    18  1978       2 PE         M                  22
##  8     12459     3     2  1987       2 PE         F                  22
##  9     13992     1    24  1988       2 PE         M                  22
## 10     14516     5    15  1988       2 PE         F                  22
## # ... with 1,289 more rows, and 5 more variables: weight &lt;dbl&gt;,
## #   genus &lt;chr&gt;, species &lt;chr&gt;, taxa &lt;chr&gt;, plot_type &lt;chr&gt;</code></pre>
</div>
<div id="select-columns-with-select" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Select columns with <code>select()</code></h3>
<p>Often your data contains variables you don’t need for the analysis you are performing, or you want to subset them to share with others.
To select only the ones you need, or explore subsets of the variables, the
<code>select()</code> verb enables you to keep only the columns of interest.</p>
<p>Figure <a href="data-wrangle-1.html#fig:dplyr-select">2.6</a> shows the use of <code>select()</code> to choose only
the <code>year</code> and <code>plot_type</code> columns, with or without the pipe.</p>
<p>Selecting the variables contained in the columns can be done in various ways.
For example, by the column number, the variable name or by range.
Check the help function <code>?select</code> for more options.</p>

<div class="figure" style="text-align: center"><span id="fig:dplyr-select"></span>
<img src="img/dplyr_select.png" alt="dplyr::select()" width="100%" />
<p class="caption">
Figure 2.6: <code>dplyr::select()</code>
</p>
</div>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="co"># Select the year and plot type columns</span></a>
<a class="sourceLine" id="cb43-2" title="2">surveys <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(year,plot_type)</a></code></pre></div>
<pre><code>## # A tibble: 34,786 x 2
##     year plot_type
##    &lt;dbl&gt; &lt;chr&gt;    
##  1  1977 Control  
##  2  1977 Control  
##  3  1977 Control  
##  4  1977 Control  
##  5  1977 Control  
##  6  1977 Control  
##  7  1977 Control  
##  8  1978 Control  
##  9  1978 Control  
## 10  1978 Control  
## # ... with 34,776 more rows</code></pre>
<p>We can also use negative selection by adding a minus sign <code>-</code> to variables we
wish to discard. Here we discard <code>sex</code>,<code>hindfoot_length</code> and <code>weight</code> from the
<code>surveys_filtered</code> object and keep everything else:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="co"># Select everything except sex, hindfoot and weight</span></a>
<a class="sourceLine" id="cb45-2" title="2">surveys_filtered <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>sex,<span class="op">-</span>hindfoot_length,<span class="op">-</span>weight)</a></code></pre></div>
<pre><code>## # A tibble: 20,729 x 10
##    record_id month   day  year plot_id species_id genus species taxa 
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;
##  1         1     7    16  1977       2 NL         Neot~ albigu~ Rode~
##  2        72     8    19  1977       2 NL         Neot~ albigu~ Rode~
##  3       224     9    13  1977       2 NL         Neot~ albigu~ Rode~
##  4       266    10    16  1977       2 NL         Neot~ albigu~ Rode~
##  5       349    11    12  1977       2 NL         Neot~ albigu~ Rode~
##  6       363    11    12  1977       2 NL         Neot~ albigu~ Rode~
##  7       435    12    10  1977       2 NL         Neot~ albigu~ Rode~
##  8       506     1     8  1978       2 NL         Neot~ albigu~ Rode~
##  9       588     2    18  1978       2 NL         Neot~ albigu~ Rode~
## 10       661     3    11  1978       2 NL         Neot~ albigu~ Rode~
## # ... with 20,719 more rows, and 1 more variable: plot_type &lt;chr&gt;</code></pre>
</div>
<div id="create-new-variables-with-mutate" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Create new variables with <code>mutate()</code></h3>
<p>Another common task is to create a new variable or variables, often from existing data
within the data frame. For this we use the <code>mutate()</code> verb. It follows the
same syntax as for <code>filter()</code>, <code>arrange()</code> and <code>select()</code> in that the first
argument is the dataset, and the subsequent arguments are the new variables we wish
to create.</p>
<p>Figure <a href="data-wrangle-1.html#fig:dplyr-mutate">2.7</a> shows how to create a new variable <code>weight_kg</code> by
dividing the existing <code>weight</code> variable in grams by 1000.</p>

<div class="figure" style="text-align: center"><span id="fig:dplyr-mutate"></span>
<img src="img/dplyr-mutate-16-10-2019.png" alt="dplyr::mutate()" width="100%" />
<p class="caption">
Figure 2.7: <code>dplyr::mutate()</code>
</p>
</div>
<p>A more complicated mutation, and key to to our analysis exploring the question
as to whether Kangaroo rats effect the size of the granivore population would
be to create a variable that indicates which type of rodent an observation is
recording.</p>
<p>To do this we can make use of another <code>dplyr</code> function called <code>case_when()</code>.
This allows us to pass different values to our new <code>rodent_type</code> variable <strong>if</strong>
they match either <code>species_id</code> values corresponding with Kangaroo rats or Granivores.</p>
<p>To remind us, the rodents species surveyed are:</p>
<p><strong>Kangaroo Rats</strong></p>
<table>
<thead>
<tr class="header">
<th>species_id</th>
<th>Scientific name</th>
<th>Common name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DM</td>
<td>Dipodomys merriami</td>
<td>Merriam’s kangaroo rat</td>
</tr>
<tr class="even">
<td>DO</td>
<td>Dipodomys ordii</td>
<td>Ord’s kangaroo rat</td>
</tr>
<tr class="odd">
<td>DS</td>
<td>Dipodomys spectabilis</td>
<td>Banner-tailed kangaroo rat</td>
</tr>
</tbody>
</table>
<p><strong>Granivores</strong></p>
<table>
<thead>
<tr class="header">
<th>species_id</th>
<th>Scientific name</th>
<th>Common name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PP</td>
<td>Chaetodipus penicillatus</td>
<td>Desert pocket mouse</td>
</tr>
<tr class="even">
<td>PF</td>
<td>Perognathus flavus</td>
<td>Silky pocket mouse</td>
</tr>
<tr class="odd">
<td>PE</td>
<td>Peromyscus eremicus</td>
<td>Cactus mouse</td>
</tr>
<tr class="even">
<td>PM</td>
<td>Peromyscus maniculatus</td>
<td>Deer Mouse</td>
</tr>
<tr class="odd">
<td>RM</td>
<td>Reithrodontomys megalotis</td>
<td>Western harvest mouse</td>
</tr>
</tbody>
</table>
<p>The first argument to <code>case_when()</code> is the variable and value we want to match,
just like <code>filter()</code>, for example <code>species_id == "DM"</code>, and then we use the tilde
operator <code>~</code> followed by the value we want give our new variable <strong>if</strong> a we match
this condition. Here we want our new variable <code>rodent_type</code> to be “Kangaroo Rat”.</p>
<p>We do this for every case we want to match. There are other species than rodents
in this data, and we have choice to either provide values for each one, ignore them
which will lead to the value <code>NA</code> for those rows or we can supply a single value
to the rest by giving the argument <code>TRUE</code> followed by the value. This means if
there are other values in <code>species_id</code> - if this is true - then give them all the
same value. Here we supply the value “Other” for the remaining species: <code>TRUE ~ "Other"</code>.</p>
<p>Below is how this looks in practice and is assigned to a new <code>surveys_mutated</code> object.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="co"># Mutate surveys_filtered</span></a>
<a class="sourceLine" id="cb47-2" title="2">surveys_mutated &lt;-<span class="st"> </span>surveys_filtered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb47-3" title="3"><span class="st">  </span><span class="co"># Create rodent type variable for K-rats and Granivores.Everything else, Other.</span></a>
<a class="sourceLine" id="cb47-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">rodent_type =</span> <span class="kw">case_when</span>(</a>
<a class="sourceLine" id="cb47-5" title="5">         species_id <span class="op">==</span><span class="st"> &quot;DM&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb47-6" title="6">         species_id <span class="op">==</span><span class="st"> &quot;DO&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb47-7" title="7">         species_id <span class="op">==</span><span class="st"> &quot;DS&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb47-8" title="8">         species_id <span class="op">==</span><span class="st"> &quot;PP&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb47-9" title="9">         species_id <span class="op">==</span><span class="st"> &quot;PF&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb47-10" title="10">         species_id <span class="op">==</span><span class="st"> &quot;PE&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb47-11" title="11">         species_id <span class="op">==</span><span class="st"> &quot;PM&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb47-12" title="12">         species_id <span class="op">==</span><span class="st"> &quot;RM&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb47-13" title="13">         <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;Other&quot;</span>))</a>
<a class="sourceLine" id="cb47-14" title="14"></a>
<a class="sourceLine" id="cb47-15" title="15"><span class="co"># Check output using distinct()</span></a>
<a class="sourceLine" id="cb47-16" title="16">surveys_mutated <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(species_id,rodent_type) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb47-17" title="17"><span class="st">        </span><span class="kw">distinct</span>(species_id, <span class="dt">.keep_all =</span> T)</a></code></pre></div>
<pre><code>## # A tibble: 42 x 2
##    species_id rodent_type 
##    &lt;chr&gt;      &lt;chr&gt;       
##  1 NL         Other       
##  2 DM         Kangaroo Rat
##  3 PF         Granivore   
##  4 PE         Granivore   
##  5 DS         Kangaroo Rat
##  6 PP         Granivore   
##  7 SH         Other       
##  8 OT         Other       
##  9 DO         Kangaroo Rat
## 10 OX         Other       
## # ... with 32 more rows</code></pre>
</div>
<div id="grouped-summaries-with-group_by-and-summarise" class="section level3">
<h3><span class="header-section-number">2.3.5</span> Grouped summaries with <code>group_by()</code> and <code>summarise()</code></h3>
<p>Finally we’ll look at the verb <code>summarise()</code> and it’s companion <code>group_by()</code>.</p>
<p><code>summarise()</code> collapses a data frame
into a single row. For example as shown in Figure <a href="data-wrangle-1.html#fig:dplyr-summarise">2.8</a>, we
could use it to find the average weight
of all the animals surveyed in the original data frame using <code>mean()</code>. (Here the
<code>na.rm = TRUE</code> argument is given to remove missing values from the data,
otherwise R would return <code>NA</code> when trying to average.)</p>


<div class="figure" style="text-align: center"><span id="fig:dplyr-summarise"></span>
<img src="img/dplyr-summarise-16-10-2019.png" alt="dplyr::summarise()" width="100%" />
<p class="caption">
Figure 2.8: <code>dplyr::summarise()</code>
</p>
</div>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1">surveys <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb49-2" title="2"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_weight =</span> <span class="kw">mean</span>(weight, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   mean_weight
##         &lt;dbl&gt;
## 1        42.7</code></pre>
<p>However <code>summarise()</code> is most useful when paired with <code>group_by()</code>
which defines the variables upon which we operate upon.</p>
<p>Figure <a href="data-wrangle-1.html#fig:group-by">2.9</a> shows how by grouping the observations according to the
<code>sex</code> and <code>species_id</code> variables, we can then calculate the <code>mean_weight</code> for
each of these groups.</p>
<div class="figure" style="text-align: center"><span id="fig:group-by"></span>
<img src="img/dplyr-group-by-16-10-2019.png" alt="dplyr::group_by()" width="100%" />
<p class="caption">
Figure 2.9: <code>dplyr::group_by()</code>
</p>
</div>
<p>Using <code>group_by()</code> with <code>summarise()</code> now returns a table with 92 rows instead of single row.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1">surveys <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb51-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(sex, species_id) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb51-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_weight =</span> <span class="kw">mean</span>(weight, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</a></code></pre></div>
<pre><code>## # A tibble: 92 x 3
## # Groups:   sex [3]
##    sex   species_id mean_weight
##    &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;
##  1 F     BA                9.16
##  2 F     DM               41.6 
##  3 F     DO               48.5 
##  4 F     DS              118.  
##  5 F     NL              154.  
##  6 F     OL               31.1 
##  7 F     OT               24.8 
##  8 F     OX               21   
##  9 F     PB               30.2 
## 10 F     PE               22.8 
## # ... with 82 more rows</code></pre>
</div>
</div>
<div id="using-dpylr-to-explore-the-effect-of-kangaroo-rat-exclusion-on-granivore-populations" class="section level2">
<h2><span class="header-section-number">2.4</span> Using <code>dpylr</code> to explore the effect of Kangaroo Rat exclusion on Granivore populations</h2>
<p>Let’s use what we’ve learnt so far to explore the effect of Kangaroo Rats on Granivore populations
for the entire time covered in the <code>surveys</code> dataset.</p>
<p>A line plot with time on the x-axis and number of rodents on the y-axis would be
one way to visual this, comparing the observations between the control plots and the Kangaroo
rat exclusion plots.</p>
<p>One way to do this is to:</p>
<ol style="list-style-type: decimal">
<li><code>filter()</code> the observations for the control and exclusion plots.</li>
<li>Create a new <code>rodent_type</code> variable for Kangaroo Rats and Granivores.</li>
<li>Create a new variable for time from the existing <code>day</code>,<code>month</code> and <code>year</code> variables.</li>
<li>Group the data according to the <code>rodent_type</code>, <code>plot_type</code> our time variable, and use <code>summarise()</code> to calculate the number of observations for each group.</li>
</ol>
<div id="re-cap-of-filter-and-mutate" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Re-cap of <code>filter()</code> and <code>mutate()</code></h3>
<p>Let’s re-cap steps one and two:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="co"># Keep only the rows corresponding with the Control and Long-term Krat Exclosure</span></a>
<a class="sourceLine" id="cb53-2" title="2">surveys_filtered &lt;-<span class="st"> </span>surveys <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb53-3" title="3"><span class="st">        </span><span class="kw">filter</span>(plot_type <span class="op">==</span><span class="st"> &quot;Control&quot;</span> <span class="op">|</span><span class="st"> </span>plot_type <span class="op">==</span><span class="st"> &quot;Long-term Krat Exclosure&quot;</span>)</a>
<a class="sourceLine" id="cb53-4" title="4"></a>
<a class="sourceLine" id="cb53-5" title="5"><span class="co"># Mutate surveys_filtered</span></a>
<a class="sourceLine" id="cb53-6" title="6">surveys_mutated &lt;-<span class="st"> </span>surveys_filtered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb53-7" title="7"><span class="st">  </span><span class="co"># Create rodent type variable for K-rats and Granivores.Everything else, Other.</span></a>
<a class="sourceLine" id="cb53-8" title="8"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">rodent_type =</span> <span class="kw">case_when</span>(</a>
<a class="sourceLine" id="cb53-9" title="9">         species_id <span class="op">==</span><span class="st"> &quot;DM&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb53-10" title="10">         species_id <span class="op">==</span><span class="st"> &quot;DO&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb53-11" title="11">         species_id <span class="op">==</span><span class="st"> &quot;DS&quot;</span> <span class="op">~</span><span class="st"> &quot;Kangaroo Rat&quot;</span>,</a>
<a class="sourceLine" id="cb53-12" title="12">         species_id <span class="op">==</span><span class="st"> &quot;PP&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb53-13" title="13">         species_id <span class="op">==</span><span class="st"> &quot;PF&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb53-14" title="14">         species_id <span class="op">==</span><span class="st"> &quot;PE&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb53-15" title="15">         species_id <span class="op">==</span><span class="st"> &quot;PM&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb53-16" title="16">         species_id <span class="op">==</span><span class="st"> &quot;RM&quot;</span> <span class="op">~</span><span class="st"> &quot;Granivore&quot;</span>,</a>
<a class="sourceLine" id="cb53-17" title="17">         <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;Other&quot;</span>))</a></code></pre></div>
</div>
<div id="use-lubridate-to-create-new-time-variables" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Use <code>lubridate</code> to create new time variables</h3>
<p>Step three introduces the tidyverse <a href="https://lubridate.tidyverse.org/"><code>lubridate</code> package</a>.
As the name suggests, this is a package for wrangling dates and times.</p>
<p>It would be clearer to plot the data on three month (quarterly) basis rather than
plotting every date in the dataset, so we need to create a variable that contains
the quarter in which the observation was made, for each observation.</p>
<p>From <code>lubridate</code> we will use the function <code>make_date()</code> in combination with <code>mutate()</code>
first to create a single column <code>date</code> variable from the <code>day</code>,<code>month</code> and <code>year</code> variables.
We then use this <code>date</code> variable to create another new variable containing a value for the
quarter of the year in which the observation was made <code>quarter</code> using the <code>quarter()</code> function.</p>
<p>We’ll assign this output to a new data frame called <code>surveys_subset</code>.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1"><span class="kw">library</span>(lubridate)</a>
<a class="sourceLine" id="cb54-2" title="2">surveys_subset &lt;-<span class="st"> </span>surveys_mutated <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb54-3" title="3"><span class="st">        </span><span class="kw">mutate</span>(<span class="dt">date =</span> <span class="kw">make_date</span>(<span class="dt">day =</span> day, <span class="dt">month =</span> month, <span class="dt">year =</span> year), </a>
<a class="sourceLine" id="cb54-4" title="4">               <span class="dt">quarter =</span> <span class="kw">quarter</span>(date,<span class="dt">with_year =</span> <span class="ot">TRUE</span>))</a></code></pre></div>
</div>
<div id="group-and-summarise-the-data-into-quarterly-observations" class="section level3">
<h3><span class="header-section-number">2.4.3</span> Group and summarise the data into quarterly observations</h3>
<p>Step four is to group and summarise our quarterly observations.</p>
<p>We group by <code>rodent_type</code>, <code>plot_type</code> and
<code>quarter</code> variables. In other words we’ve grouped the data according to Kangaroo Rat or
Granivore, Control plot or Exclusion plot, and the quarter of the year in which
the observation occurred.</p>
<p>Then we can calculate the number of captures for each of these groups by
using <code>summarise()</code> to create a <code>mean_captures</code> variable which is equal to the number
of rows for that group using the <code>n()</code> function divided by 4 to calculate
the average over each quarter.</p>
<p><strong>Note:</strong> <code>n()</code> is a <code>dplyr</code> function that returns the number of observations in the current group.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1">by_quarter &lt;-<span class="st"> </span>surveys_subset <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb55-2" title="2"><span class="st">        </span><span class="kw">group_by</span>(rodent_type,plot_type,quarter) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb55-3" title="3"><span class="st">        </span><span class="kw">summarise</span>(<span class="dt">mean_captures =</span> <span class="kw">n</span>()<span class="op">/</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb55-4" title="4"></a>
<a class="sourceLine" id="cb55-5" title="5">by_quarter</a></code></pre></div>
<pre><code>## # A tibble: 567 x 4
## # Groups:   rodent_type, plot_type [6]
##    rodent_type plot_type quarter mean_captures
##    &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt;         &lt;dbl&gt;
##  1 Granivore   Control     1977.          3.75
##  2 Granivore   Control     1977.          2   
##  3 Granivore   Control     1978.          2.75
##  4 Granivore   Control     1978.          2.25
##  5 Granivore   Control     1978.          3.25
##  6 Granivore   Control     1978.          1   
##  7 Granivore   Control     1979.          1.25
##  8 Granivore   Control     1979.          1.5 
##  9 Granivore   Control     1979.          1.25
## 10 Granivore   Control     1980.          5.5 
## # ... with 557 more rows</code></pre>
<p>These steps have taken us from a table of 34,786 observations to a table of 567 observations.</p>
</div>
<div id="create-a-plot-with-ggplot" class="section level3">
<h3><span class="header-section-number">2.4.4</span> Create a plot with <code>ggplot</code></h3>
<p>Now we can create a line and point plot, using the <code>by_quarter</code> data as our first <code>ggplot()</code>
argument.</p>
<p>For the aesthetics we are plotting the time on the
x-axis using the <code>quarter</code> variable, and the quarterly <code>mean_captures</code> on the
y-axis, and we colour the data by <code>rodent_type</code>.</p>
<p>Then we create line and point geometric mappings, and split the plot into two
facets using <code>facet_wrap</code> according to <code>plot_type</code>.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1"><span class="kw">ggplot</span>(by_quarter,</a>
<a class="sourceLine" id="cb57-2" title="2">       <span class="kw">aes</span>(<span class="dt">x=</span>quarter,<span class="dt">y=</span>mean_captures,<span class="dt">colour=</span>rodent_type)) <span class="op">+</span></a>
<a class="sourceLine" id="cb57-3" title="3"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb57-4" title="4"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb57-5" title="5"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>plot_type)</a></code></pre></div>
<pre><code>## Warning: Removed 2 rows containing missing values (geom_path).</code></pre>
<pre><code>## Warning: Removed 5 rows containing missing values (geom_point).</code></pre>
<p><img src="coding-together_files/figure-html/plot-quarter-all-1.png" width="100%" /></p>
<p>But it would be more useful to only plot the Kangaroo Rats and Granivores
data, so let’s filter out the other species. And move the legend to the bottom
of the plot and add a title.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1">by_quarter <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb60-2" title="2"><span class="st">        </span><span class="kw">filter</span>(rodent_type <span class="op">!=</span><span class="st"> &quot;Other&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb60-3" title="3"><span class="st">        </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>quarter,<span class="dt">y=</span>mean_captures,<span class="dt">colour=</span>rodent_type)) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-4" title="4"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb60-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb60-6" title="6"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>plot_type) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-7" title="7"><span class="st">        </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;bottom&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-8" title="8"><span class="st">        </span><span class="kw">ggtitle</span>(<span class="st">&quot;How does excluding Kangaroo Rats </span></a>
<a class="sourceLine" id="cb60-9" title="9"><span class="st">                effect Granivore populations?&quot;</span>, </a>
<a class="sourceLine" id="cb60-10" title="10">                <span class="dt">subtitle =</span> <span class="st">&quot;Mean quarterly observations&quot;</span>)</a></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_path).</code></pre>
<pre><code>## Warning: Removed 3 rows containing missing values (geom_point).</code></pre>
<p><img src="coding-together_files/figure-html/plot-quarter-1.png" width="100%" /></p>
<blockquote>
<p><strong>Challenge</strong> Can you do a similar analysis, but plotting the data only from 1980 to 2000 and by semester?</p>
</blockquote>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="getting-started.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-wrangle-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["coding-together.pdf"],
"toc": {
"collapse": "section"
},
"css": "style.css"
});
});
</script>

</body>

</html>
